//! [`DecisionLog`] + [`DecisionPath`] — explain trail for the `ExplainDecision`
//! RPC (S2.3 §20 / Appendix A).
//!
//! ## What this lands (T-024)
//!
//! - [`DecisionPath`] — the per-decision breadcrumb trail: the §3 step
//!   names that fired, the §5 precedence-tier that produced the terminal
//!   outcome, a free-text narrative, and the decision itself.
//! - [`DecisionLog`] — bounded ring-buffer keyed by `policy_decision_id`,
//!   wrapped in `Arc<RwLock<...>>` so the gRPC adapter can read while the
//!   pipeline writes.
//!
//! ## Bounded by design
//!
//! `DecisionLog::with_capacity(N)` keeps at most `N` recent decisions; the
//! oldest is evicted on overflow. This is the minimum surface needed to
//! satisfy the §20 `ExplainDecision(policy_decision_id) -> ExplainDecisionResponse`
//! contract without unbounded memory growth.
//!
//! ## Future evolution
//!
//! M5 lands the persistent S3.1 evidence log; at that point the
//! `ExplainDecision` RPC can fall through to the evidence log when the
//! decision is older than the ring-buffer window. T-024 ships the in-memory
//! window only.

use std::collections::HashMap;
use std::collections::VecDeque;
use std::sync::{Arc, RwLock};

use serde::{Deserialize, Serialize};

use crate::decision::PolicyDecision;

/// Default ring-buffer window (entries) for [`DecisionLog::default`].
///
/// 1 024 mirrors the [`crate::cache::DEFAULT_CAPACITY`]; sized for the
/// §22 acceptance workload plus operator-visible recent-decisions UI.
pub const DEFAULT_LOG_CAPACITY: usize = 1024;

/// The breadcrumb trail recorded for one decision (T-024).
///
/// Surfaced over the `ExplainDecision` RPC; the proto-level
/// `ExplainDecisionResponse` has `decision`, `rule_chain[]`, `narrative`,
/// `enrichment_snapshot` fields — this struct carries the first three
/// directly. The `enrichment_snapshot` proto field is populated at the
/// gRPC adapter from the decision's `enrichment_snapshot_id` lookup.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DecisionPath {
    /// The final decision itself (S2.3 §4 — 14-field shape).
    pub decision: PolicyDecision,
    /// Ordered rule ids that contributed to the outcome. Empty when the
    /// decision is a default-deny or a hard-deny (constitutional, not
    /// bundle-authored). Bundle-authored decisions populate this list.
    pub rule_chain: Vec<String>,
    /// Human-readable plain text describing the §5 precedence path that
    /// produced the outcome. Generated by the pipeline at decision-emit
    /// time; the audit replay tooling can re-derive it from the decision +
    /// `rule_chain` if needed.
    pub narrative: String,
}

impl DecisionPath {
    /// Construct a [`DecisionPath`] from the canonical pipeline output.
    ///
    /// The `narrative` defaults to a §5-tier description anchored on the
    /// decision's `reason_code`; callers can override via [`Self::with_narrative`].
    #[must_use]
    pub fn from_decision(decision: PolicyDecision) -> Self {
        let narrative = format!(
            "decision={:?} reason={} rules_consulted={}",
            decision.decision, decision.reason_code, decision.rules_consulted
        );
        Self {
            decision,
            rule_chain: Vec::new(),
            narrative,
        }
    }

    /// Fluent setter for the rule chain.
    #[must_use]
    pub fn with_rule_chain(mut self, chain: Vec<String>) -> Self {
        self.rule_chain = chain;
        self
    }

    /// Fluent setter for the narrative.
    #[must_use]
    pub fn with_narrative(mut self, narrative: impl Into<String>) -> Self {
        self.narrative = narrative.into();
        self
    }
}

/// Bounded ring-buffer keyed by `policy_decision_id` (T-024).
///
/// The pipeline writes a new entry after step 11; the `ExplainDecision`
/// RPC reads from the same log. Internally the log is two co-ordinated
/// structures:
///
/// - a [`HashMap`] for `O(1)` lookup by `policy_decision_id`,
/// - a [`VecDeque`] for `O(1)` FIFO ordering (so eviction is also `O(1)`).
///
/// Both are kept in sync by the `record` / `evict_oldest` helpers; the
/// invariant is `map.len() == queue.len()` after every public call.
pub struct DecisionLog {
    capacity: usize,
    map: HashMap<String, DecisionPath>,
    queue: VecDeque<String>,
}

impl std::fmt::Debug for DecisionLog {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("DecisionLog")
            .field("capacity", &self.capacity)
            .field("len", &self.map.len())
            .finish_non_exhaustive()
    }
}

impl Default for DecisionLog {
    fn default() -> Self {
        Self::with_capacity(DEFAULT_LOG_CAPACITY)
    }
}

impl DecisionLog {
    /// Construct a fresh log with the given window size.
    ///
    /// `capacity == 0` collapses to [`DEFAULT_LOG_CAPACITY`] for the same
    /// reasoning as [`crate::cache::DecisionCache::new`].
    #[must_use]
    pub fn with_capacity(capacity: usize) -> Self {
        let cap = if capacity == 0 {
            DEFAULT_LOG_CAPACITY
        } else {
            capacity
        };
        Self {
            capacity: cap,
            map: HashMap::with_capacity(cap),
            queue: VecDeque::with_capacity(cap),
        }
    }

    /// Record a decision in the log. Evicts the oldest entry when the
    /// window is full. Re-recording an existing `policy_decision_id`
    /// overwrites the path (this should not happen in practice — ids are
    /// per-evaluation — but the defensive overwrite is the safer default).
    pub fn record(&mut self, path: DecisionPath) {
        let id = path.decision.policy_decision_id.clone();
        // Idiomatic single-lookup: `Entry::occupied/vacant`. On occupied
        // we overwrite without disturbing the queue; on vacant we evict
        // oldest if full, then enqueue + insert.
        if let std::collections::hash_map::Entry::Occupied(mut e) = self.map.entry(id.clone()) {
            e.insert(path);
            return;
        }
        if self.map.len() >= self.capacity {
            if let Some(oldest) = self.queue.pop_front() {
                self.map.remove(&oldest);
            }
        }
        self.queue.push_back(id.clone());
        self.map.insert(id, path);
    }

    /// Look up a previously-recorded decision path by id.
    #[must_use]
    pub fn get(&self, policy_decision_id: &str) -> Option<DecisionPath> {
        self.map.get(policy_decision_id).cloned()
    }

    /// Current entry count.
    #[must_use]
    pub fn len(&self) -> usize {
        self.map.len()
    }

    /// `true` when the log holds no entries.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.map.is_empty()
    }

    /// Configured window size.
    #[must_use]
    pub const fn capacity(&self) -> usize {
        self.capacity
    }
}

/// Thread-safe wrapper around [`DecisionLog`].
///
/// Mirror of [`crate::cache::SharedDecisionCache`]: `Arc<RwLock<...>>`
/// newtype with poisoning-tolerant lock acquisition. The gRPC adapter
/// holds one of these; the pipeline-side `record` and the RPC-side `get`
/// share the same instance.
#[derive(Clone, Default)]
pub struct SharedDecisionLog {
    inner: Arc<RwLock<DecisionLog>>,
}

impl std::fmt::Debug for SharedDecisionLog {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SharedDecisionLog")
            .field("inner", &"<Arc<RwLock<DecisionLog>>>")
            .finish()
    }
}

impl SharedDecisionLog {
    /// Construct a fresh shared log with the given window.
    #[must_use]
    pub fn with_capacity(capacity: usize) -> Self {
        Self {
            inner: Arc::new(RwLock::new(DecisionLog::with_capacity(capacity))),
        }
    }

    /// Record a decision path. Lock-and-forward.
    pub fn record(&self, path: DecisionPath) {
        let mut guard = match self.inner.write() {
            Ok(g) => g,
            Err(poisoned) => poisoned.into_inner(),
        };
        guard.record(path);
    }

    /// Look up a previously-recorded path. Lock-and-forward.
    #[must_use]
    pub fn get(&self, policy_decision_id: &str) -> Option<DecisionPath> {
        let guard = match self.inner.read() {
            Ok(g) => g,
            Err(poisoned) => poisoned.into_inner(),
        };
        guard.get(policy_decision_id)
    }

    /// Current entry count.
    #[must_use]
    pub fn len(&self) -> usize {
        let guard = match self.inner.read() {
            Ok(g) => g,
            Err(poisoned) => poisoned.into_inner(),
        };
        guard.len()
    }

    /// `true` when the log holds no entries.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        let guard = match self.inner.read() {
            Ok(g) => g,
            Err(poisoned) => poisoned.into_inner(),
        };
        guard.is_empty()
    }
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::panic,
    clippy::unwrap_used,
    reason = "test code; panic-on-failure is the idiomatic test signal"
)]
mod tests {
    use super::*;
    use crate::decision::{Decision, PolicyDecision};
    use chrono::Utc;

    fn fixture_path(id: &str) -> DecisionPath {
        let decision = PolicyDecision {
            policy_decision_id: id.to_owned(),
            action_id: aios_action::ActionId::default(),
            request_hash: "rh".into(),
            bundle_version: "polb_v1".into(),
            enrichment_snapshot_id: "polb_snap_x".into(),
            decision: Decision::Deny,
            reason_code: "Test".into(),
            reason_message: "test".into(),
            constraints: crate::constraints::Constraints::default(),
            approval: crate::constraints::ApprovalRequirement::default(),
            evidence_receipt_id: String::new(),
            evaluated_at: Utc::now(),
            rules_consulted: 0,
            simulated: false,
        };
        DecisionPath::from_decision(decision)
    }

    #[test]
    fn record_then_get_round_trip() {
        let mut log = DecisionLog::with_capacity(4);
        log.record(fixture_path("poldec_a"));
        let back = log.get("poldec_a").unwrap();
        assert_eq!(back.decision.policy_decision_id, "poldec_a");
    }

    #[test]
    fn ring_buffer_evicts_oldest_on_overflow() {
        let mut log = DecisionLog::with_capacity(2);
        log.record(fixture_path("poldec_a"));
        log.record(fixture_path("poldec_b"));
        log.record(fixture_path("poldec_c"));
        assert!(log.get("poldec_a").is_none());
        assert!(log.get("poldec_b").is_some());
        assert!(log.get("poldec_c").is_some());
    }

    #[test]
    fn capacity_zero_falls_back_to_default() {
        let log = DecisionLog::with_capacity(0);
        assert_eq!(log.capacity(), DEFAULT_LOG_CAPACITY);
    }

    #[test]
    fn shared_log_round_trip() {
        let log = SharedDecisionLog::with_capacity(4);
        log.record(fixture_path("poldec_a"));
        let back = log.get("poldec_a").unwrap();
        assert_eq!(back.decision.policy_decision_id, "poldec_a");
        assert_eq!(log.len(), 1);
    }

    #[test]
    fn from_decision_populates_narrative() {
        let p = fixture_path("poldec_a");
        assert!(p.narrative.contains("decision="));
        assert!(p.narrative.contains("reason="));
    }
}
