//! Rust ↔ proto translations for the gRPC `PolicyKernel` surface (T-023).
//!
//! The crate exposes two parallel type hierarchies:
//!
//! 1. **Rust value types** — [`crate::Decision`], [`crate::PolicyDecision`],
//!    [`crate::Constraints`], [`crate::ApprovalRequirement`], the typed
//!    [`crate::PolicyError`] taxonomy. These are spec-typed with closed enums
//!    (`EvidenceGrade`, `NetworkPolicy`, `SessionClass`, `ApprovalScope`,
//!    `ApproverClass`) that prevent invalid combinations at compile time.
//!
//! 2. **Proto message types** — generated by `tonic-build` from
//!    `proto/aios.policy.v1alpha1.proto`. These are the wire shape per S2.3
//!    Appendix A: 14-field [`crate::service::proto::PolicyDecision`] envelope,
//!    11-field `Constraints`, 5-field `ApprovalRequirement`, etc. The closed
//!    string fields (`network_policy`, `min_subject_session_class`,
//!    `require_evidence_grade`, `approval_scope`, `approver_classes[]`) are
//!    proto `string`s because proto3 does not natively support typed enums
//!    inside repeated fields without losing the unknown-value tolerance the
//!    spec asks for; the conversions here re-parse them into the closed Rust
//!    enums on the way out.
//!
//! ## Closed-string ↔ closed-enum bridge
//!
//! The bundle / decision wire form uses **lowercase tokens for instance-level
//! enums** (`approval_scope = "exact_request_hash"`, `approver_classes =
//! ["human", "operator"]`) but **`SCREAMING_SNAKE_CASE`** for top-level
//! discriminants (`Decision = ALLOW | REQUIRE_APPROVAL | DENY`,
//! `NetworkPolicy = LOCALHOST_ONLY | LAN_ALLOWED | INTERNET_ALLOWED`,
//! `SessionClass = PUBLIC | INTERNAL | CONFIDENTIAL | RESTRICTED | RECOVERY`,
//! `EvidenceGrade = E2 | E3 | E4 | E5`). This mirrors the spec §4 / §10 / §11.2
//! token tables verbatim — drift on either side is a wire-format break.
//!
//! ## Status code mapping (S2.3 §18.2 wire path)
//!
//! [`policy_error_to_status`] maps the typed [`crate::PolicyError`] surface
//! onto `tonic::Status` per the §18.2 failure-mode table. The mapping is the
//! single source of truth for how the wire boundary reports policy-side
//! failures — RPC-level transport failures (timeouts, cancellation,
//! connection drops) are surfaced by tonic itself with the canonical
//! `Code::Cancelled` / `Code::DeadlineExceeded` / `Code::Unavailable` codes
//! and never flow through this function.

// `tonic::Status` is intentionally a wide value type (carries headers,
// metadata, source error, …). The `result_large_err` lint flags every
// `Result<_, Status>` return — boxing the error would only push allocations
// onto the hot path of a wire surface that is already designed for typed
// status propagation. Allow it at module scope; the alternative is to
// re-box everywhere the conversions/server modules return a Status, which
// fights the tonic API ergonomics.
#![allow(clippy::result_large_err)]

use chrono::{DateTime, TimeZone, Utc};
use prost_types::Timestamp;

use crate::bundle::{
    PolicyBundle as RustPolicyBundle, PolicyRule as RustPolicyRule, RuleEffect, RuleScope,
};
use crate::constraints::{
    ApprovalRequirement, ApprovalScope, ApproverClass, Constraints, EvidenceGrade, NetworkPolicy,
    SandboxProfileId, SessionClass, VaultCapabilityId,
};
use crate::decision::{Decision, PolicyDecision};
use crate::error::PolicyError;
use crate::service::proto;

// ---------------------------------------------------------------------------
// Timestamp helpers (chrono::DateTime<Utc> <-> prost_types::Timestamp)
// ---------------------------------------------------------------------------

/// Convert a `chrono::DateTime<Utc>` into the prost well-known `Timestamp`.
///
/// Lossless for every instant chrono can represent (`i64` seconds since the
/// Unix epoch + nanos).
#[must_use]
pub fn datetime_to_proto(dt: DateTime<Utc>) -> Timestamp {
    Timestamp {
        seconds: dt.timestamp(),
        // `timestamp_subsec_nanos` returns a `u32` in `0..1_000_000_000`,
        // which fits into the proto `i32` field by construction.
        nanos: i32::try_from(dt.timestamp_subsec_nanos()).unwrap_or(0),
    }
}

/// Convert the prost well-known `Timestamp` back into `chrono::DateTime<Utc>`.
///
/// Returns the Unix epoch (`1970-01-01T00:00:00Z`) when the proto value is
/// out of range — this matches the "wire defect, decision must still emit"
/// discipline of S2.3 §3 (no silent fall-through; every envelope produces a
/// decision; the audit trail records the wire defect via the calling RPC's
/// `reason_code`).
#[must_use]
pub fn datetime_from_proto(ts: Timestamp) -> DateTime<Utc> {
    Utc.timestamp_opt(ts.seconds, u32::try_from(ts.nanos).unwrap_or(0))
        .single()
        .unwrap_or_else(|| Utc.timestamp_opt(0, 0).single().unwrap_or_default())
}

// ---------------------------------------------------------------------------
// Decision <-> proto::Decision
// ---------------------------------------------------------------------------

/// Convert the crate's hand-written closed [`Decision`] enum into the
/// prost-generated wire enum.
#[must_use]
pub const fn decision_to_proto(d: Decision) -> proto::Decision {
    match d {
        Decision::Unspecified => proto::Decision::Unspecified,
        Decision::Allow => proto::Decision::Allow,
        Decision::RequireApproval => proto::Decision::RequireApproval,
        Decision::Deny => proto::Decision::Deny,
    }
}

/// Convert the prost-generated wire enum back to the crate's hand-written
/// closed enum.
///
/// `Decision::Unspecified` round-trips as-is so callers can detect proto3
/// zero-value sentinels; production code never produces it.
#[must_use]
pub const fn decision_from_proto(p: proto::Decision) -> Decision {
    match p {
        proto::Decision::Unspecified => Decision::Unspecified,
        proto::Decision::Allow => Decision::Allow,
        proto::Decision::RequireApproval => Decision::RequireApproval,
        proto::Decision::Deny => Decision::Deny,
    }
}

// ---------------------------------------------------------------------------
// NetworkPolicy / SessionClass / EvidenceGrade <-> closed wire strings
// ---------------------------------------------------------------------------

/// Wire-string encoding for [`NetworkPolicy`] (§10 row 7).
#[must_use]
pub const fn network_policy_to_str(np: NetworkPolicy) -> &'static str {
    match np {
        NetworkPolicy::LocalhostOnly => "LOCALHOST_ONLY",
        NetworkPolicy::LanAllowed => "LAN_ALLOWED",
        NetworkPolicy::InternetAllowed => "INTERNET_ALLOWED",
    }
}

/// Inverse of [`network_policy_to_str`]; empty / unknown returns `None`.
#[must_use]
pub fn network_policy_from_str(s: &str) -> Option<NetworkPolicy> {
    match s {
        "LOCALHOST_ONLY" => Some(NetworkPolicy::LocalhostOnly),
        "LAN_ALLOWED" => Some(NetworkPolicy::LanAllowed),
        "INTERNET_ALLOWED" => Some(NetworkPolicy::InternetAllowed),
        _ => None,
    }
}

/// Wire-string encoding for [`SessionClass`] (§10 row 9).
#[must_use]
pub const fn session_class_to_str(sc: SessionClass) -> &'static str {
    match sc {
        SessionClass::Public => "PUBLIC",
        SessionClass::Internal => "INTERNAL",
        SessionClass::Confidential => "CONFIDENTIAL",
        SessionClass::Restricted => "RESTRICTED",
        SessionClass::Recovery => "RECOVERY",
    }
}

/// Inverse of [`session_class_to_str`]; empty / unknown returns `None`.
#[must_use]
pub fn session_class_from_str(s: &str) -> Option<SessionClass> {
    match s {
        "PUBLIC" => Some(SessionClass::Public),
        "INTERNAL" => Some(SessionClass::Internal),
        "CONFIDENTIAL" => Some(SessionClass::Confidential),
        "RESTRICTED" => Some(SessionClass::Restricted),
        "RECOVERY" => Some(SessionClass::Recovery),
        _ => None,
    }
}

/// Wire-string encoding for [`EvidenceGrade`] (§10 row 5).
#[must_use]
pub const fn evidence_grade_to_str(eg: EvidenceGrade) -> &'static str {
    match eg {
        EvidenceGrade::E2 => "E2",
        EvidenceGrade::E3 => "E3",
        EvidenceGrade::E4 => "E4",
        EvidenceGrade::E5 => "E5",
    }
}

/// Inverse of [`evidence_grade_to_str`]; empty / unknown returns `None`.
#[must_use]
pub fn evidence_grade_from_str(s: &str) -> Option<EvidenceGrade> {
    match s {
        "E2" => Some(EvidenceGrade::E2),
        "E3" => Some(EvidenceGrade::E3),
        "E4" => Some(EvidenceGrade::E4),
        "E5" => Some(EvidenceGrade::E5),
        _ => None,
    }
}

/// Wire-string encoding for [`ApprovalScope`] (§11.2 / §15).
#[must_use]
pub const fn approval_scope_to_str(s: ApprovalScope) -> &'static str {
    match s {
        ApprovalScope::ExactRequestHash => "exact_request_hash",
    }
}

/// Empty / unknown wire values collapse to the rev.2 default per spec.
///
/// Inverse of [`approval_scope_to_str`]; empty falls back to the rev.2 default
/// per spec ("only value in rev.2"). Unknown values also collapse to the
/// default — the trust boundary keeps the wire form forward-compatible.
#[must_use]
pub const fn approval_scope_from_str(_s: &str) -> ApprovalScope {
    ApprovalScope::ExactRequestHash
}

/// Wire-string encoding for [`ApproverClass`] (§11.2 / §15 / §7).
#[must_use]
pub const fn approver_class_to_str(c: ApproverClass) -> &'static str {
    match c {
        ApproverClass::Human => "human",
        ApproverClass::Operator => "operator",
        ApproverClass::Agent => "agent",
        ApproverClass::Application => "application",
        ApproverClass::Service => "service",
        ApproverClass::Device => "device",
        ApproverClass::Workflow => "workflow",
        ApproverClass::RemoteOperator => "remote_operator",
    }
}

/// Inverse of [`approver_class_to_str`].
///
/// Unknown tokens are dropped silently (so a future approver class added by a
/// newer bundle does not crash an older client — only the closed set known
/// here participates in the approval-pipeline match).
#[must_use]
pub fn approver_class_from_str(s: &str) -> Option<ApproverClass> {
    match s {
        "human" => Some(ApproverClass::Human),
        "operator" => Some(ApproverClass::Operator),
        "agent" => Some(ApproverClass::Agent),
        "application" => Some(ApproverClass::Application),
        "service" => Some(ApproverClass::Service),
        "device" => Some(ApproverClass::Device),
        "workflow" => Some(ApproverClass::Workflow),
        "remote_operator" => Some(ApproverClass::RemoteOperator),
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// Constraints <-> proto::Constraints
// ---------------------------------------------------------------------------

/// Convert the Rust [`Constraints`] vocabulary into the wire envelope.
///
/// Per §10 the proto3 wire form uses default values (empty string / 0) as
/// the "unset" signal — there is no `Option<...>` on the wire. The Rust
/// type carries explicit `Option<T>` for those fields to keep the model
/// faithful; the conversion collapses `None` to the empty / zero default.
#[must_use]
pub fn constraints_to_proto(c: &Constraints) -> proto::Constraints {
    proto::Constraints {
        sandbox_profile_id: c
            .sandbox_profile_id
            .as_ref()
            .map_or_else(String::new, |s| s.0.clone()),
        max_runtime_seconds: c.max_runtime_seconds.unwrap_or(0),
        verification_required: c.verification_required,
        dry_run_only: c.dry_run_only,
        require_evidence_grade: c
            .require_evidence_grade
            .map_or_else(String::new, |g| evidence_grade_to_str(g).to_owned()),
        require_human_co_signer: c.require_human_co_signer,
        network_policy: c
            .network_policy
            .map_or_else(String::new, |n| network_policy_to_str(n).to_owned()),
        max_concurrent_per_subject: c.max_concurrent_per_subject.unwrap_or(0),
        min_subject_session_class: c
            .min_subject_session_class
            .map_or_else(String::new, |s| session_class_to_str(s).to_owned()),
        vault_capability_required: c
            .vault_capability_required
            .as_ref()
            .map_or_else(String::new, |v| v.0.clone()),
        ttl_seconds: c.ttl_seconds,
    }
}

/// Inverse of [`constraints_to_proto`] — wire defaults map back to `None`.
///
/// Unknown closed-enum tokens (`network_policy`, `min_subject_session_class`,
/// `require_evidence_grade`) are mapped to `None` rather than rejected — the
/// proto3 `string` wire form is forward-compatible by design, and the
/// decision pipeline can still emit a `DENY` with a reason code when a
/// constraint is unknown. The strict reject path lives in
/// [`Constraints::validate`] on the typed Rust side.
#[must_use]
pub fn constraints_from_proto(p: &proto::Constraints) -> Constraints {
    Constraints {
        sandbox_profile_id: (!p.sandbox_profile_id.is_empty())
            .then(|| SandboxProfileId(p.sandbox_profile_id.clone())),
        max_runtime_seconds: (p.max_runtime_seconds != 0).then_some(p.max_runtime_seconds),
        verification_required: p.verification_required,
        dry_run_only: p.dry_run_only,
        require_evidence_grade: evidence_grade_from_str(&p.require_evidence_grade),
        require_human_co_signer: p.require_human_co_signer,
        network_policy: network_policy_from_str(&p.network_policy),
        max_concurrent_per_subject: (p.max_concurrent_per_subject != 0)
            .then_some(p.max_concurrent_per_subject),
        min_subject_session_class: session_class_from_str(&p.min_subject_session_class),
        vault_capability_required: (!p.vault_capability_required.is_empty())
            .then(|| VaultCapabilityId(p.vault_capability_required.clone())),
        ttl_seconds: p.ttl_seconds,
        // `expires_at` is a Rust-side audit helper (§13); it has no proto
        // wire counterpart so the round-trip collapses it to `None`. The
        // decision pipeline reconstructs the effective expiry from
        // `evaluated_at + ttl_seconds` per §13.2.
        expires_at: None,
    }
}

// ---------------------------------------------------------------------------
// ApprovalRequirement <-> proto::ApprovalRequirement
// ---------------------------------------------------------------------------

/// Convert the Rust [`ApprovalRequirement`] into the wire envelope.
#[must_use]
pub fn approval_to_proto(a: &ApprovalRequirement) -> proto::ApprovalRequirement {
    proto::ApprovalRequirement {
        required: a.required,
        approval_scope: approval_scope_to_str(a.approval_scope).to_owned(),
        ttl_seconds: a.ttl_seconds,
        approver_classes: a
            .approver_classes
            .iter()
            .map(|c| approver_class_to_str(*c).to_owned())
            .collect(),
        require_human_co_signer: a.require_human_co_signer,
    }
}

/// Inverse of [`approval_to_proto`].
///
/// Unknown `approver_classes` tokens are silently dropped (forward-compat per
/// the closed-string discipline above).
#[must_use]
pub fn approval_from_proto(p: &proto::ApprovalRequirement) -> ApprovalRequirement {
    ApprovalRequirement {
        required: p.required,
        approval_scope: approval_scope_from_str(&p.approval_scope),
        ttl_seconds: p.ttl_seconds,
        approver_classes: p
            .approver_classes
            .iter()
            .filter_map(|s| approver_class_from_str(s))
            .collect(),
        require_human_co_signer: p.require_human_co_signer,
    }
}

// ---------------------------------------------------------------------------
// PolicyDecision <-> proto::PolicyDecision
// ---------------------------------------------------------------------------

/// Convert the Rust [`PolicyDecision`] (14 fields per §4) into the wire form.
#[must_use]
pub fn policy_decision_to_proto(d: &PolicyDecision) -> proto::PolicyDecision {
    proto::PolicyDecision {
        policy_decision_id: d.policy_decision_id.clone(),
        action_id: d.action_id.as_str().to_owned(),
        request_hash: d.request_hash.clone(),
        bundle_version: d.bundle_version.clone(),
        enrichment_snapshot_id: d.enrichment_snapshot_id.clone(),
        decision: decision_to_proto(d.decision) as i32,
        reason_code: d.reason_code.clone(),
        reason_message: d.reason_message.clone(),
        constraints: Some(constraints_to_proto(&d.constraints)),
        approval: Some(approval_to_proto(&d.approval)),
        evidence_receipt_id: d.evidence_receipt_id.clone(),
        evaluated_at: Some(datetime_to_proto(d.evaluated_at)),
        rules_consulted: d.rules_consulted,
        simulated: d.simulated,
    }
}

/// Inverse of [`policy_decision_to_proto`].
///
/// Missing nested `constraints` / `approval` collapse to the Rust defaults.
/// Missing `evaluated_at` collapses to the Unix epoch (the caller's audit
/// trail will record the wire defect via `reason_code`).
#[must_use]
pub fn policy_decision_from_proto(p: &proto::PolicyDecision) -> PolicyDecision {
    PolicyDecision {
        policy_decision_id: p.policy_decision_id.clone(),
        // `aios_action::ActionId` parses from the canonical `<prefix>_<ULID>`
        // form; on a malformed wire id we fall back to a fresh ULID-shaped
        // sentinel so the round-trip never panics. Production rejects the
        // request before it reaches this code path; the conversion is for
        // tests + audit replay.
        action_id: aios_action::ActionId::parse(&p.action_id)
            .unwrap_or_else(|_| aios_action::ActionId::default()),
        request_hash: p.request_hash.clone(),
        bundle_version: p.bundle_version.clone(),
        enrichment_snapshot_id: p.enrichment_snapshot_id.clone(),
        decision: decision_from_proto(
            proto::Decision::try_from(p.decision).unwrap_or(proto::Decision::Unspecified),
        ),
        reason_code: p.reason_code.clone(),
        reason_message: p.reason_message.clone(),
        constraints: p
            .constraints
            .as_ref()
            .map(constraints_from_proto)
            .unwrap_or_default(),
        approval: p
            .approval
            .as_ref()
            .map(approval_from_proto)
            .unwrap_or_default(),
        evidence_receipt_id: p.evidence_receipt_id.clone(),
        evaluated_at: p.evaluated_at.map_or_else(
            || Utc.timestamp_opt(0, 0).single().unwrap_or_default(),
            datetime_from_proto,
        ),
        rules_consulted: p.rules_consulted,
        simulated: p.simulated,
    }
}

// ---------------------------------------------------------------------------
// PolicyError -> tonic::Status (S2.3 §18.2 wire-path failure mapping)
// ---------------------------------------------------------------------------

/// Map a typed [`PolicyError`] to a `tonic::Status` per S2.3 §18.2.
///
/// The wire boundary uses three canonical gRPC codes:
///
/// - `Unauthenticated` — subject hydration failed (§7). The provisional id
///   is unknown / expired / revoked; the three failure modes collapse at the
///   policy boundary per §7 so identity-existence does not leak.
/// - `InvalidArgument` — schema invalid (§3 step 1), bundle JSON malformed,
///   condition parse / eval failure, constraints invalid. All of these are
///   caller-supplied wire defects.
/// - `FailedPrecondition` — bundle load / signature / version-pin / authority
///   failures, enrichment-unavailable. The engine is structurally degraded
///   per §12.3 / §18.2 — the caller cannot fix it by retrying with a
///   different payload.
///
/// The decision-side codes (`PolicyEvaluationTimeout`, `PolicyEngineInternal`)
/// are NOT raised through this function — the engine emits them as a typed
/// `DENY` decision per §18.2, not as a gRPC error. This function is the
/// **boundary** between policy-side typed errors and the wire surface;
/// in-band decisions flow through `policy_decision_to_proto`.
#[must_use]
pub fn policy_error_to_status(err: &PolicyError) -> tonic::Status {
    match err {
        PolicyError::SubjectUnauthenticated => {
            tonic::Status::unauthenticated("subject hydration failed: subject unauthenticated")
        }
        PolicyError::EnrichmentUnavailable => {
            tonic::Status::failed_precondition("resource enrichment unavailable")
        }
        PolicyError::BundleLoad { reason } => {
            tonic::Status::failed_precondition(format!("policy bundle load failed: {reason}"))
        }
        PolicyError::SchemaInvalid { detail } => {
            tonic::Status::invalid_argument(format!("policy bundle schema invalid: {detail}"))
        }
        PolicyError::ConstraintsInvalid(d) => {
            tonic::Status::invalid_argument(format!("constraints invalid: {d}"))
        }
        PolicyError::ConditionParse(d) => {
            tonic::Status::invalid_argument(format!("condition parse failed: {d}"))
        }
        PolicyError::ConditionEval(d) => {
            tonic::Status::invalid_argument(format!("condition eval failed: {d}"))
        }
        PolicyError::InvalidPolicyBundle(d) => {
            tonic::Status::invalid_argument(format!("invalid policy bundle: {d}"))
        }
        PolicyError::BundleSignatureInvalid => {
            tonic::Status::failed_precondition("bundle signature invalid")
        }
        PolicyError::BundleVersionMismatch { expected, found } => {
            tonic::Status::failed_precondition(format!(
                "bundle version mismatch: expected {expected}, found {found}"
            ))
        }
        PolicyError::BundleUnknownAuthority(a) => {
            tonic::Status::failed_precondition(format!("bundle signed by unknown authority: {a}"))
        }
    }
}

// ---------------------------------------------------------------------------
// ActionEnvelope <-> envelope_proto bytes (JSON placeholder per task #26)
// ---------------------------------------------------------------------------

/// Encode an `aios_action::ActionEnvelope` into the wire-bytes form expected
/// by `EvaluatePolicyRequest.envelope_proto`.
///
/// Per task #26 in the .ai tracker, the in-tree wire format is the canonical
/// `serde_json` representation of the envelope. When `aios-action` ships
/// its own proto IDL, this function is the single touch point — the rest
/// of the service module references it by name.
///
/// # Errors
///
/// Returns `tonic::Status::internal` when serialisation fails. In practice
/// this cannot happen for a well-typed `ActionEnvelope` (the serde derive
/// is infallible over the value), but we surface the error for forward
/// compatibility with future fields that may carry a fallible serializer.
pub fn envelope_to_bytes(env: &aios_action::ActionEnvelope) -> Result<Vec<u8>, tonic::Status> {
    serde_json::to_vec(env)
        .map_err(|e| tonic::Status::internal(format!("envelope serialize failed: {e}")))
}

/// Decode the wire-bytes form of `EvaluatePolicyRequest.envelope_proto`.
///
/// See [`envelope_to_bytes`] for the format. Decode failures surface as
/// `tonic::Code::InvalidArgument` because the bytes are caller-supplied and
/// a malformed envelope is a wire defect (§18.2: caller-fixable).
///
/// # Errors
///
/// Returns `tonic::Status::invalid_argument` when the bytes are empty or
/// when `serde_json` cannot deserialize the payload into an `ActionEnvelope`.
pub fn envelope_from_bytes(bytes: &[u8]) -> Result<aios_action::ActionEnvelope, tonic::Status> {
    if bytes.is_empty() {
        return Err(tonic::Status::invalid_argument(
            "envelope_proto is empty (expected serialized aios.action.v1alpha1.ActionEnvelope)",
        ));
    }
    serde_json::from_slice(bytes).map_err(|e| {
        tonic::Status::invalid_argument(format!(
            "envelope_proto deserialize failed (JSON placeholder per task #26): {e}"
        ))
    })
}

// ---------------------------------------------------------------------------
// proto::PolicyBundle  ->  Rust PolicyBundle  (T-024 LoadBundle bridge)
// ---------------------------------------------------------------------------

/// Map the proto `RuleEffect` enum onto the Rust closed enum (T-024 — the
/// `LoadBundle` bridge).
#[must_use]
pub const fn rule_effect_from_proto(e: i32) -> RuleEffect {
    // proto enum: 0 unspecified, 1 allow, 2 deny
    match e {
        1 => RuleEffect::Allow,
        2 => RuleEffect::Deny,
        _ => RuleEffect::Unspecified,
    }
}

/// Bridge a `proto::PolicyRule` onto the Rust [`crate::PolicyRule`]
/// (T-024 — the `LoadBundle` bridge).
///
/// The proto rule has no `scope` / `reason_code` field; both are
/// synthesised from the proto rule's existing fields:
///
/// - `scope` defaults to [`RuleScope::Global`] (the broadest matcher;
///   future revs of the proto schema will carry an explicit field).
/// - `reason_code` is taken from `metadata.policy_pack` when present, or
///   from `rule_id` as a fallback so the audit chain still resolves.
#[must_use]
pub fn proto_rule_to_rust(p: &proto::PolicyRule) -> RustPolicyRule {
    let reason_code = p
        .metadata
        .as_ref()
        .map(|m| m.policy_pack.clone())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| p.rule_id.clone());
    RustPolicyRule {
        rule_id: p.rule_id.clone(),
        scope: RuleScope::Global,
        effect: rule_effect_from_proto(p.effect),
        priority: p.priority,
        subjects: p.subjects.clone(),
        actions: p.actions.clone(),
        conditions: p.conditions.clone(),
        constraints: p.constraints.as_ref().map(constraints_from_proto),
        approval: p.approval.as_ref().map(approval_from_proto),
        reason_code,
    }
}

/// Bridge a `proto::PolicyBundle` onto the Rust
/// [`crate::PolicyBundle`] (T-024 — the `LoadBundle` bridge).
///
/// Field aliasing:
///
/// - `publisher_id`         → `signing_authority`
/// - `publisher_signature`  → `signature_ed25519`
/// - `bundle_version`       → `bundle_version` (identical)
/// - `created_at`           → `created_at`; falls back to Unix epoch when
///   the proto timestamp is missing.
/// - `bundle_id`            is synthesised from `bundle_version` (the
///   proto schema does not yet carry a separate `bundle_id` field; T-025
///   adds it).
///
/// The rules list is converted via [`proto_rule_to_rust`]; the
/// `group_definitions` / `aios_root_signature` / `hard_denies` proto
/// fields are not yet represented on the Rust side and are dropped.
///
/// # Errors
///
/// Returns [`PolicyError::InvalidPolicyBundle`] when the publisher
/// signature is not the canonical 64-byte Ed25519 length.
pub fn proto_bundle_to_rust(p: &proto::PolicyBundle) -> Result<RustPolicyBundle, PolicyError> {
    let created_at = p.created_at.as_ref().map_or_else(
        || Utc.timestamp_opt(0, 0).single().unwrap_or_default(),
        |t| datetime_from_proto(*t),
    );
    if p.publisher_signature.len() != 64 {
        return Err(PolicyError::InvalidPolicyBundle(format!(
            "publisher_signature must be 64 bytes (got {})",
            p.publisher_signature.len()
        )));
    }
    Ok(RustPolicyBundle {
        bundle_version: p.bundle_version.clone(),
        bundle_id: p.bundle_version.clone(),
        created_at,
        signing_authority: p.publisher_id.clone(),
        signature_ed25519: p.publisher_signature.clone(),
        rules: p.rules.iter().map(proto_rule_to_rust).collect(),
    })
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::panic,
    clippy::unwrap_used,
    reason = "test code; panic-on-failure is the idiomatic test signal"
)]
mod tests {
    use super::*;
    use aios_action::ActionId;

    fn sample_constraints() -> Constraints {
        Constraints {
            sandbox_profile_id: Some(SandboxProfileId("host-service-control".into())),
            max_runtime_seconds: Some(60),
            verification_required: true,
            dry_run_only: false,
            require_evidence_grade: Some(EvidenceGrade::E3),
            require_human_co_signer: true,
            network_policy: Some(NetworkPolicy::LanAllowed),
            max_concurrent_per_subject: Some(4),
            min_subject_session_class: Some(SessionClass::Internal),
            vault_capability_required: Some(VaultCapabilityId("vault.read".into())),
            ttl_seconds: 300,
            expires_at: None,
        }
    }

    fn sample_approval() -> ApprovalRequirement {
        ApprovalRequirement {
            required: true,
            approval_scope: ApprovalScope::ExactRequestHash,
            ttl_seconds: 600,
            approver_classes: vec![ApproverClass::Human, ApproverClass::Operator],
            require_human_co_signer: false,
        }
    }

    fn sample_decision() -> PolicyDecision {
        PolicyDecision {
            policy_decision_id: "poldec_01JABCDEFGHJKMNPQRSTVWXYZ".into(),
            action_id: ActionId::default(),
            request_hash: "abc123".into(),
            bundle_version: "polb_01234567".into(),
            enrichment_snapshot_id: "snap_xyz".into(),
            decision: Decision::Allow,
            reason_code: "ScopedAllow".into(),
            reason_message: "matched rule allow_lucky".into(),
            constraints: sample_constraints(),
            approval: sample_approval(),
            evidence_receipt_id: "evr_aaaaa".into(),
            evaluated_at: Utc.timestamp_opt(1_700_000_000, 42_000_000).unwrap(),
            rules_consulted: 7,
            simulated: false,
        }
    }

    #[test]
    fn decision_proto_round_trip_covers_all_four_variants() {
        for d in [
            Decision::Unspecified,
            Decision::Allow,
            Decision::RequireApproval,
            Decision::Deny,
        ] {
            let p = decision_to_proto(d);
            assert_eq!(d, decision_from_proto(p));
        }
    }

    #[test]
    fn constraints_proto_round_trip_preserves_every_field() {
        let mut expected = sample_constraints();
        let p = constraints_to_proto(&expected);
        let back = constraints_from_proto(&p);
        // `expires_at` does not survive the round-trip (no wire counterpart);
        // every other field must.
        expected.expires_at = None;
        assert_eq!(expected, back);
    }

    #[test]
    fn approval_proto_round_trip_preserves_approver_classes_order() {
        let a = sample_approval();
        let p = approval_to_proto(&a);
        let back = approval_from_proto(&p);
        assert_eq!(a, back);
    }

    #[test]
    fn policy_decision_proto_round_trip_preserves_all_14_fields_modulo_expires_at() {
        let d = sample_decision();
        let p = policy_decision_to_proto(&d);
        let back = policy_decision_from_proto(&p);
        // `expires_at` is the only audit-helper field with no proto mirror
        // (§4 has 14 wire fields; `expires_at` is a Rust-side helper).
        assert_eq!(d, back);
    }

    #[test]
    fn datetime_round_trip_is_lossless_to_nano_precision() {
        let t = Utc.timestamp_opt(1_700_000_000, 123_456_789).unwrap();
        let p = datetime_to_proto(t);
        let back = datetime_from_proto(p);
        assert_eq!(t, back);
    }

    #[test]
    fn closed_strings_round_trip_for_every_variant() {
        for np in [
            NetworkPolicy::LocalhostOnly,
            NetworkPolicy::LanAllowed,
            NetworkPolicy::InternetAllowed,
        ] {
            assert_eq!(Some(np), network_policy_from_str(network_policy_to_str(np)));
        }
        for sc in [
            SessionClass::Public,
            SessionClass::Internal,
            SessionClass::Confidential,
            SessionClass::Restricted,
            SessionClass::Recovery,
        ] {
            assert_eq!(Some(sc), session_class_from_str(session_class_to_str(sc)));
        }
        for eg in [
            EvidenceGrade::E2,
            EvidenceGrade::E3,
            EvidenceGrade::E4,
            EvidenceGrade::E5,
        ] {
            assert_eq!(Some(eg), evidence_grade_from_str(evidence_grade_to_str(eg)));
        }
        for ac in [
            ApproverClass::Human,
            ApproverClass::Operator,
            ApproverClass::Agent,
            ApproverClass::Application,
            ApproverClass::Service,
            ApproverClass::Device,
            ApproverClass::Workflow,
            ApproverClass::RemoteOperator,
        ] {
            assert_eq!(Some(ac), approver_class_from_str(approver_class_to_str(ac)));
        }
    }

    #[test]
    fn policy_error_maps_to_correct_status_codes() {
        use tonic::Code;
        assert_eq!(
            policy_error_to_status(&PolicyError::SubjectUnauthenticated).code(),
            Code::Unauthenticated
        );
        assert_eq!(
            policy_error_to_status(&PolicyError::EnrichmentUnavailable).code(),
            Code::FailedPrecondition
        );
        assert_eq!(
            policy_error_to_status(&PolicyError::BundleSignatureInvalid).code(),
            Code::FailedPrecondition
        );
        assert_eq!(
            policy_error_to_status(&PolicyError::BundleVersionMismatch {
                expected: "polb_1".into(),
                found: "polb_2".into(),
            })
            .code(),
            Code::FailedPrecondition
        );
        assert_eq!(
            policy_error_to_status(&PolicyError::BundleUnknownAuthority("acme".into())).code(),
            Code::FailedPrecondition
        );
        assert_eq!(
            policy_error_to_status(&PolicyError::SchemaInvalid {
                detail: "bad schema".into(),
            })
            .code(),
            Code::InvalidArgument
        );
        assert_eq!(
            policy_error_to_status(&PolicyError::ConstraintsInvalid("zero ttl".into())).code(),
            Code::InvalidArgument
        );
        assert_eq!(
            policy_error_to_status(&PolicyError::ConditionParse("bad ns".into())).code(),
            Code::InvalidArgument
        );
        assert_eq!(
            policy_error_to_status(&PolicyError::ConditionEval("type mismatch".into())).code(),
            Code::InvalidArgument
        );
        assert_eq!(
            policy_error_to_status(&PolicyError::InvalidPolicyBundle("malformed".into())).code(),
            Code::InvalidArgument
        );
        assert_eq!(
            policy_error_to_status(&PolicyError::BundleLoad {
                reason: "io".into(),
            })
            .code(),
            Code::FailedPrecondition
        );
    }
}
