//! Rust ↔ proto translations for the gRPC `EvidenceLog` surface (T-011).
//!
//! The crate exposes two parallel type hierarchies:
//!
//! 1. **Rust value types** — [`crate::EvidenceReceipt`], [`crate::record::RecordType`],
//!    [`crate::record::RetentionClass`]. These are the chain-of-custody types with
//!    type-level append-only enforcement (INV-005), Ed25519 signatures, and the
//!    full 427-entry record vocabulary as a closed enum.
//!
//! 2. **Proto message types** — generated by `tonic-build` from
//!    `proto/aios.evidence.v1alpha1.proto`. These are the wire shape per S3.1
//!    Appendix A: the full 17-field [`crate::service::proto::EvidenceReceipt`]
//!    envelope, the discriminated `RecordPayload` one-of, request/response
//!    messages, etc.
//!
//! The two hierarchies are intentionally separate: the Rust types prevent
//! mutation at compile time, the proto types are the bidirectional wire
//! contract. This module is the single bridge.
//!
//! ## Field mapping (T-011 subset of the 17-field proto envelope)
//!
//! | Proto field                  | Rust source                             | Notes                       |
//! | ---------------------------- | --------------------------------------- | --------------------------- |
//! | `receipt_id`                  | `EvidenceReceipt::receipt_id()`         | `evr_<ULID>`                |
//! | `recorded_at`                 | `EvidenceReceipt::recorded_at()`        | Timestamp seconds + nanos   |
//! | `record_type`                 | `EvidenceReceipt::record_type()`        | Proto enum int              |
//! | `subject`                     | `EvidenceReceipt::subject_canonical_id` | S5.1 subject string         |
//! | `action_id`                   | `EvidenceReceipt::action_id()`          | Empty string if `None`      |
//! | `policy_decision_id`           | _carry-forward_                         | Always empty in T-011       |
//! | `verification_id`              | _carry-forward_                         | Always empty in T-011       |
//! | `correlation_id`               | _carry-forward_                         | Always empty in T-011       |
//! | `trace_id`                    | _carry-forward_                         | Always empty in T-011       |
//! | `segment_id`                  | _carry-forward_                         | Always empty in T-011       |
//! | `sequence_number`             | _carry-forward_                         | Always 0 in T-011           |
//! | `payload_hash`                | `EvidenceReceipt::content_hash()`       | 64-char hex                 |
//! | `payload_ref`                 | _carry-forward_                         | Always empty in T-011       |
//! | `redaction_profile`            | _carry-forward_                         | Always empty in T-011       |
//! | `previous_receipt_hash`        | `EvidenceReceipt::previous_receipt_hash`| Empty string if `None`      |
//! | `simulated`                   | _carry-forward_                         | Always false in T-011       |
//! | `payload`                     | _carry-forward_                         | One-of left empty in T-011  |
//!
//! The carry-forward fields are §22.4 / Wave 14 reconciliation items. The
//! Rust types are extended without breaking the wire format when those
//! reconciliations land; this conversion module is the only file that needs
//! to change.

use chrono::{DateTime, TimeZone, Utc};
use prost_types::Timestamp;

use crate::record::{RecordType, RetentionClass};
use crate::service::proto;
use crate::EvidenceError;
use crate::EvidenceReceipt;

// ---------------------------------------------------------------------------
// RetentionClass <-> i32 (proto does not include RetentionClass in the wire
// envelope; it is metadata on the in-memory append path. We still expose a
// stable string representation so `Append` can carry it via headers if
// needed in a future Wave.)
// ---------------------------------------------------------------------------

/// Default retention class assumed at `Append` time when no override is
/// supplied in the request. Maps to S3.1 §13 default `Standard24M`.
pub const DEFAULT_RETENTION: RetentionClass = RetentionClass::Standard24M;

// ---------------------------------------------------------------------------
// RecordType <-> proto::RecordType
// ---------------------------------------------------------------------------

/// Convert the crate's hand-written closed [`RecordType`] enum into the
/// prost-generated wire enum.
///
/// Both enums share Rust `PascalCase` variant names by design (T-008 / Wave 13
/// vocabulary lock); the proto's `as_str_name()` returns the wire
/// `SCREAMING_SNAKE_CASE` string and our `RecordType::as_wire_str()` is
/// constructed to match it. We translate via the shared wire string,
/// guaranteeing that any drift between the two would be caught by the
/// `record_type_round_trips_through_proto` test in `impl_inmemory.rs`.
#[must_use]
pub fn record_type_to_proto(rt: RecordType) -> proto::RecordType {
    // `from_str_name` is the inverse of `as_str_name`; the proto enum carries
    // a default unspecified variant. We unwrap by falling back to
    // `Unspecified` for safety, but the test suite proves that every crate
    // variant has a matching proto variant — so this fallback never fires
    // in practice.
    proto::RecordType::from_str_name(rt.as_wire_str()).unwrap_or(proto::RecordType::Unspecified)
}

/// Convert the prost-generated wire enum back to the crate's hand-written
/// closed enum.
///
/// # Errors
///
/// Returns [`EvidenceError::EncodingFailed`] when the proto value is
/// `RECORD_TYPE_UNSPECIFIED` or otherwise outside the 1..=427 vocabulary —
/// both indicate a wire-format defect (the spec freezes 1..=427 with the
/// 1000..9999 range reserved for forward expansion).
pub fn record_type_from_proto(p: proto::RecordType) -> Result<RecordType, EvidenceError> {
    let name = p.as_str_name();
    record_type_from_wire_str(name)
}

/// Same conversion as [`record_type_from_proto`] but starts from the raw
/// proto int (as carried by `EvidenceReceipt.record_type` on the wire).
///
/// # Errors
///
/// Returns [`EvidenceError::EncodingFailed`] when the int value is outside
/// the proto enum or maps to `RECORD_TYPE_UNSPECIFIED`.
pub fn record_type_from_proto_i32(value: i32) -> Result<RecordType, EvidenceError> {
    let p = proto::RecordType::try_from(value).map_err(|_| {
        EvidenceError::EncodingFailed(format!(
            "wire RecordType value {value} is outside the proto vocabulary"
        ))
    })?;
    record_type_from_proto(p)
}

/// Lookup helper: turn a `SCREAMING_SNAKE_CASE` wire name into the crate's
/// [`RecordType`]. Used by both proto translation and Wave 14 payload
/// reconciliation tooling.
///
/// # Errors
///
/// Returns [`EvidenceError::EncodingFailed`] for unknown or unspecified
/// names.
pub fn record_type_from_wire_str(name: &str) -> Result<RecordType, EvidenceError> {
    use strum::IntoEnumIterator as _;
    if name == "RECORD_TYPE_UNSPECIFIED" {
        return Err(EvidenceError::EncodingFailed(
            "wire RecordType is RECORD_TYPE_UNSPECIFIED (proto3 default); rejecting".to_owned(),
        ));
    }
    RecordType::iter()
        .find(|rt| rt.as_wire_str() == name)
        .ok_or_else(|| {
            EvidenceError::EncodingFailed(format!(
                "wire RecordType `{name}` is not part of the closed §29 vocabulary"
            ))
        })
}

// ---------------------------------------------------------------------------
// chrono::DateTime<Utc> <-> prost_types::Timestamp
// ---------------------------------------------------------------------------

/// Convert a `chrono::DateTime<Utc>` to a `prost_types::Timestamp`.
///
/// `Timestamp` is `(seconds: i64, nanos: i32)` per Google's well-known type;
/// `chrono` exposes `timestamp()` (seconds) and `timestamp_subsec_nanos()`.
#[must_use]
pub const fn datetime_to_timestamp(dt: DateTime<Utc>) -> Timestamp {
    // chrono returns sub-second nanos as u32 in 0..1_000_000_000; the
    // cast to i32 is always safe in that range.
    #[allow(
        clippy::cast_possible_wrap,
        reason = "u32 value is bounded < 1e9, fits in i32"
    )]
    let nanos = dt.timestamp_subsec_nanos() as i32;
    Timestamp {
        seconds: dt.timestamp(),
        nanos,
    }
}

/// Convert a `prost_types::Timestamp` to a `chrono::DateTime<Utc>`.
///
/// Out-of-range timestamps fold to `Utc.timestamp_opt(0, 0)` (the Unix
/// epoch) — the production engine never emits such values (T-009 stamps via
/// `Utc::now()`), so this is purely a defence against malicious wire data.
#[must_use]
pub fn timestamp_to_datetime(ts: &Timestamp) -> DateTime<Utc> {
    // `timestamp_opt` returns `LocalResult<DateTime<Utc>>`; we use
    // `single()` which yields the valid value when there's exactly one.
    // Negative nanos are clamped to 0 to defend against malformed wire data.
    #[allow(
        clippy::cast_sign_loss,
        reason = "max(0) clamps to non-negative before the cast"
    )]
    let nanos = ts.nanos.max(0) as u32;
    Utc.timestamp_opt(ts.seconds, nanos)
        .single()
        .unwrap_or_else(|| Utc.timestamp_opt(0, 0).single().unwrap_or_default())
}

// ---------------------------------------------------------------------------
// EvidenceReceipt -> proto::EvidenceReceipt
// ---------------------------------------------------------------------------

/// Project a crate-native [`EvidenceReceipt`] onto the 17-field proto wire
/// envelope.
///
/// Carry-forward fields (see the table in this module's doc comment) are
/// emitted as their proto3 defaults (empty string, zero, `false`, `None`).
/// This is the documented T-011 carry-forward stance; Wave 14 reconciles
/// payload + correlation fields.
#[must_use]
pub fn receipt_to_proto(r: &EvidenceReceipt) -> proto::EvidenceReceipt {
    proto::EvidenceReceipt {
        receipt_id: r.receipt_id().as_str().to_owned(),
        recorded_at: Some(datetime_to_timestamp(r.recorded_at())),
        record_type: i32::from(record_type_to_proto(r.record_type())),
        subject: r.subject_canonical_id().to_owned(),
        action_id: r
            .action_id()
            .map(|a| a.as_str().to_owned())
            .unwrap_or_default(),
        // §22.4 carry-forward — populated by Wave 14+ as the contract extends.
        policy_decision_id: String::new(),
        verification_id: String::new(),
        correlation_id: String::new(),
        trace_id: String::new(),
        segment_id: String::new(),
        sequence_number: 0,
        payload_hash: r.content_hash().to_owned(),
        payload_ref: String::new(),
        redaction_profile: String::new(),
        previous_receipt_hash: r
            .previous_receipt_hash()
            .map(ToOwned::to_owned)
            .unwrap_or_default(),
        simulated: false,
        // Wave 14: discriminated `RecordPayload` one-of. T-011 leaves it empty.
        payload: None,
    }
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::panic,
    reason = "panic-on-failure is the idiomatic test signal"
)]
mod tests {
    use super::*;
    use crate::ReceiptBuilder;
    use serde_json::json;
    use strum::IntoEnumIterator as _;

    #[test]
    fn record_type_round_trips_through_proto_for_every_variant() {
        // Cover every entry in the closed 427-variant vocabulary. The proto
        // codegen produces the same set of variants; we assert byte-equality
        // of the wire name.
        let mut covered = 0_usize;
        for rt in RecordType::iter() {
            let p = record_type_to_proto(rt);
            assert_ne!(
                p,
                proto::RecordType::Unspecified,
                "crate RecordType::{rt:?} did not map to a non-unspecified proto variant"
            );
            assert_eq!(
                p.as_str_name(),
                rt.as_wire_str(),
                "wire-name mismatch: crate={} proto={}",
                rt.as_wire_str(),
                p.as_str_name()
            );
            let back = record_type_from_proto(p).expect("inverse conversion must succeed");
            assert_eq!(back, rt, "round-trip failed for {rt:?}");
            covered += 1;
        }
        // The strum-derived count is 427.
        assert_eq!(covered, <RecordType as strum::EnumCount>::COUNT);
        assert_eq!(covered, 427);
    }

    #[test]
    fn record_type_from_proto_rejects_unspecified() {
        let r = record_type_from_proto(proto::RecordType::Unspecified);
        match r {
            Err(EvidenceError::EncodingFailed(detail)) => {
                assert!(detail.contains("UNSPECIFIED"));
            }
            other => panic!("expected EncodingFailed for unspecified, got {other:?}"),
        }
    }

    #[test]
    fn record_type_from_proto_i32_handles_out_of_range_values() {
        // 50_000 is well outside the 1..=427 and reserved 1000..=9999 range.
        let r = record_type_from_proto_i32(50_000);
        match r {
            Err(EvidenceError::EncodingFailed(detail)) => {
                assert!(detail.contains("50000") || detail.contains("vocabulary"));
            }
            other => panic!("expected EncodingFailed for out-of-range, got {other:?}"),
        }
    }

    #[test]
    fn record_type_from_wire_str_rejects_unknown_names() {
        let r = record_type_from_wire_str("BANANA_PEELED");
        match r {
            Err(EvidenceError::EncodingFailed(detail)) => {
                assert!(detail.contains("BANANA_PEELED"));
            }
            other => panic!("expected EncodingFailed, got {other:?}"),
        }
    }

    #[test]
    fn datetime_timestamp_round_trip_preserves_seconds_and_nanos() {
        // Pick a specific time with sub-second nanos to exercise both fields.
        let dt = Utc
            .timestamp_opt(1_700_000_000, 123_456_789)
            .single()
            .expect("valid utc");
        let ts = datetime_to_timestamp(dt);
        assert_eq!(ts.seconds, 1_700_000_000);
        assert_eq!(ts.nanos, 123_456_789);
        let back = timestamp_to_datetime(&ts);
        assert_eq!(back, dt);
    }

    #[test]
    fn receipt_to_proto_populates_t011_fields_and_zeroes_carry_forward() {
        let receipt = ReceiptBuilder::new(
            RecordType::ActionReceived,
            RetentionClass::Standard24M,
            "human:operator-1",
        )
        .with_payload(json!({"action": "fs.write"}))
        .seal(None)
        .expect("seal");

        let p = receipt_to_proto(&receipt);

        // T-011 populated fields.
        assert_eq!(p.receipt_id, receipt.receipt_id().as_str());
        assert!(p.recorded_at.is_some());
        assert_eq!(p.record_type, i32::from(proto::RecordType::ActionReceived));
        assert_eq!(p.subject, "human:operator-1");
        assert_eq!(p.payload_hash, receipt.content_hash());
        assert_eq!(p.previous_receipt_hash, String::new());

        // §22.4 carry-forward defaults.
        assert_eq!(p.policy_decision_id, "");
        assert_eq!(p.verification_id, "");
        assert_eq!(p.correlation_id, "");
        assert_eq!(p.trace_id, "");
        assert_eq!(p.segment_id, "");
        assert_eq!(p.sequence_number, 0);
        assert_eq!(p.payload_ref, "");
        assert_eq!(p.redaction_profile, "");
        assert!(!p.simulated);
        assert!(p.payload.is_none());
    }

    #[test]
    fn receipt_to_proto_links_previous_receipt_hash() {
        let g = ReceiptBuilder::new(
            RecordType::ActionReceived,
            RetentionClass::Standard24M,
            "human:operator-1",
        )
        .seal(None)
        .expect("genesis");
        let n = ReceiptBuilder::new(
            RecordType::PolicyDecision,
            RetentionClass::Standard24M,
            "service:policy",
        )
        .seal(Some(&g))
        .expect("next");
        let p = receipt_to_proto(&n);
        assert_eq!(
            p.previous_receipt_hash,
            n.previous_receipt_hash().expect("present").to_owned()
        );
        // Verify the link is the 32-char link hash of the genesis.
        assert_eq!(p.previous_receipt_hash.len(), 32);
    }
}
