//! Rust ↔ proto translations for the gRPC `CapabilityRuntime` surface (T-033).
//!
//! The crate exposes two parallel type hierarchies:
//!
//! 1. **Rust value types** — [`crate::ActionLifecycleState`],
//!    [`crate::ActionDispatchKind`], [`crate::AdapterIOMode`],
//!    [`crate::AdapterStability`], [`crate::QueueClass`],
//!    [`crate::ExecutionFailureReason`], [`crate::RollbackOutcome`],
//!    [`crate::RuntimeErrorCode`], [`crate::AdapterManifest`],
//!    [`crate::RegisteredAdapter`], [`crate::ActionContext`], and the typed
//!    [`crate::RuntimeError`] taxonomy. These are spec-typed with closed
//!    enums per S10.1 §3.
//!
//! 2. **Proto message types** — generated by `tonic-build` from
//!    `proto/aios.runtime.v1alpha1.proto`. These are the wire shape per
//!    S10.1 §5.1.
//!
//! ## Status code mapping (S10.1 §3.8 / §18.x)
//!
//! [`runtime_error_to_status`] maps the typed [`crate::RuntimeError`] surface
//! onto `tonic::Status` per the closed `RuntimeErrorCode` table. The mapping
//! is the single source of truth for how the wire boundary reports runtime-
//! side failures — RPC-level transport failures (timeouts, cancellation,
//! connection drops) are surfaced by tonic itself with the canonical
//! `Code::Cancelled` / `Code::DeadlineExceeded` / `Code::Unavailable` codes
//! and never flow through this function.

// `tonic::Status` is intentionally a wide value type (carries headers,
// metadata, source error, ...). The `result_large_err` lint flags every
// `Result<_, Status>` return — boxing the error would only push allocations
// onto the hot path of a wire surface that is already designed for typed
// status propagation. Allow it at module scope; the alternative is to
// re-box everywhere the conversions/server modules return a Status, which
// fights the tonic API ergonomics.
//
// `missing_docs` is allowed at module scope because every enum mapping
// function below is a 1:1 Rust ↔ proto3 translation whose semantics are
// fully captured by its identifier (`foo_to_proto` / `foo_from_proto`).
// Documenting each individually would only echo the function name.
#![allow(clippy::result_large_err, missing_docs)]

use chrono::{DateTime, TimeZone, Utc};
use prost_types::Timestamp;

use crate::adapter_manifest::{AdapterActionDeclaration, AdapterManifest};
use crate::adapter_registry::RegisteredAdapter;
use crate::context::ActionContext;
use crate::dispatch::{ActionDispatchKind, AdapterIOMode, AdapterStability, QueueClass};
use crate::error::RuntimeError;
use crate::failure::{ExecutionFailureReason, RollbackOutcome, RuntimeErrorCode};
use crate::service::proto;
use crate::status::ActionLifecycleState;

// ---------------------------------------------------------------------------
// Timestamp helpers (chrono::DateTime<Utc> <-> prost_types::Timestamp)
// ---------------------------------------------------------------------------

/// Convert a `chrono::DateTime<Utc>` into the prost well-known `Timestamp`.
///
/// Lossless for every instant chrono can represent (`i64` seconds since the
/// Unix epoch + nanos).
#[must_use]
pub fn datetime_to_proto(dt: DateTime<Utc>) -> Timestamp {
    Timestamp {
        seconds: dt.timestamp(),
        // `timestamp_subsec_nanos` returns a `u32` in `0..1_000_000_000`,
        // which fits into the proto `i32` field by construction.
        nanos: i32::try_from(dt.timestamp_subsec_nanos()).unwrap_or(0),
    }
}

/// Convert the prost well-known `Timestamp` back into `chrono::DateTime<Utc>`.
///
/// Returns the Unix epoch when the proto value is out of range.
#[must_use]
pub fn datetime_from_proto(ts: Timestamp) -> DateTime<Utc> {
    Utc.timestamp_opt(ts.seconds, u32::try_from(ts.nanos).unwrap_or(0))
        .single()
        .unwrap_or_else(unix_epoch)
}

/// Return the Unix epoch (`1970-01-01T00:00:00Z`) as a `DateTime<Utc>`.
///
/// Used as the safe fallback when an absent / out-of-range proto timestamp
/// must still produce a typed Rust value.
#[must_use]
fn unix_epoch() -> DateTime<Utc> {
    Utc.timestamp_opt(0, 0).single().unwrap_or_default()
}

// ---------------------------------------------------------------------------
// ActionLifecycleState <-> proto enum
// ---------------------------------------------------------------------------

/// Rust → proto enum mapping for [`ActionLifecycleState`].
#[must_use]
pub const fn lifecycle_state_to_proto(s: ActionLifecycleState) -> proto::ActionLifecycleState {
    match s {
        ActionLifecycleState::Created => proto::ActionLifecycleState::Created,
        ActionLifecycleState::PolicyPending => proto::ActionLifecycleState::PolicyPending,
        ActionLifecycleState::ApprovalPending => proto::ActionLifecycleState::ApprovalPending,
        ActionLifecycleState::OverridePending => proto::ActionLifecycleState::OverridePending,
        ActionLifecycleState::Approved => proto::ActionLifecycleState::Approved,
        ActionLifecycleState::PolicyDenied => proto::ActionLifecycleState::PolicyDenied,
        ActionLifecycleState::OverrideDenied => proto::ActionLifecycleState::OverrideDenied,
        ActionLifecycleState::Queued => proto::ActionLifecycleState::Queued,
        ActionLifecycleState::Executing => proto::ActionLifecycleState::Executing,
        ActionLifecycleState::Verifying => proto::ActionLifecycleState::Verifying,
        ActionLifecycleState::Succeeded => proto::ActionLifecycleState::Succeeded,
        ActionLifecycleState::Failed => proto::ActionLifecycleState::Failed,
        ActionLifecycleState::RolledBack => proto::ActionLifecycleState::RolledBack,
        ActionLifecycleState::RollbackFailed => proto::ActionLifecycleState::RollbackFailed,
    }
}

/// proto → Rust enum mapping for [`ActionLifecycleState`].
///
/// Returns `None` when the proto carries the zero-value `_UNSPECIFIED`
/// sentinel (production code never emits it).
#[must_use]
pub const fn lifecycle_state_from_proto(
    p: proto::ActionLifecycleState,
) -> Option<ActionLifecycleState> {
    match p {
        proto::ActionLifecycleState::Unspecified => None,
        proto::ActionLifecycleState::Created => Some(ActionLifecycleState::Created),
        proto::ActionLifecycleState::PolicyPending => Some(ActionLifecycleState::PolicyPending),
        proto::ActionLifecycleState::ApprovalPending => Some(ActionLifecycleState::ApprovalPending),
        proto::ActionLifecycleState::OverridePending => Some(ActionLifecycleState::OverridePending),
        proto::ActionLifecycleState::Approved => Some(ActionLifecycleState::Approved),
        proto::ActionLifecycleState::PolicyDenied => Some(ActionLifecycleState::PolicyDenied),
        proto::ActionLifecycleState::OverrideDenied => Some(ActionLifecycleState::OverrideDenied),
        proto::ActionLifecycleState::Queued => Some(ActionLifecycleState::Queued),
        proto::ActionLifecycleState::Executing => Some(ActionLifecycleState::Executing),
        proto::ActionLifecycleState::Verifying => Some(ActionLifecycleState::Verifying),
        proto::ActionLifecycleState::Succeeded => Some(ActionLifecycleState::Succeeded),
        proto::ActionLifecycleState::Failed => Some(ActionLifecycleState::Failed),
        proto::ActionLifecycleState::RolledBack => Some(ActionLifecycleState::RolledBack),
        proto::ActionLifecycleState::RollbackFailed => Some(ActionLifecycleState::RollbackFailed),
    }
}

// ---------------------------------------------------------------------------
// ActionDispatchKind <-> proto enum
// ---------------------------------------------------------------------------

#[must_use]
pub const fn dispatch_kind_to_proto(k: ActionDispatchKind) -> proto::ActionDispatchKind {
    match k {
        ActionDispatchKind::InProcessRpc => proto::ActionDispatchKind::InProcessRpc,
        ActionDispatchKind::SubprocessFork => proto::ActionDispatchKind::SubprocessFork,
        ActionDispatchKind::IsolatedSandbox => proto::ActionDispatchKind::IsolatedSandbox,
        ActionDispatchKind::DryRun => proto::ActionDispatchKind::DryRun,
    }
}

#[must_use]
pub const fn dispatch_kind_from_proto(p: proto::ActionDispatchKind) -> Option<ActionDispatchKind> {
    match p {
        proto::ActionDispatchKind::Unspecified => None,
        proto::ActionDispatchKind::InProcessRpc => Some(ActionDispatchKind::InProcessRpc),
        proto::ActionDispatchKind::SubprocessFork => Some(ActionDispatchKind::SubprocessFork),
        proto::ActionDispatchKind::IsolatedSandbox => Some(ActionDispatchKind::IsolatedSandbox),
        proto::ActionDispatchKind::DryRun => Some(ActionDispatchKind::DryRun),
    }
}

// ---------------------------------------------------------------------------
// AdapterIOMode <-> proto enum
// ---------------------------------------------------------------------------

#[must_use]
pub const fn io_mode_to_proto(m: AdapterIOMode) -> proto::AdapterIoMode {
    match m {
        AdapterIOMode::TypedParametersOnly => proto::AdapterIoMode::TypedParametersOnly,
        AdapterIOMode::TemplateParameters => proto::AdapterIoMode::TemplateParameters,
    }
}

#[must_use]
pub const fn io_mode_from_proto(p: proto::AdapterIoMode) -> Option<AdapterIOMode> {
    match p {
        proto::AdapterIoMode::Unspecified => None,
        proto::AdapterIoMode::TypedParametersOnly => Some(AdapterIOMode::TypedParametersOnly),
        proto::AdapterIoMode::TemplateParameters => Some(AdapterIOMode::TemplateParameters),
    }
}

// ---------------------------------------------------------------------------
// AdapterStability <-> proto enum
// ---------------------------------------------------------------------------

#[must_use]
pub const fn stability_to_proto(s: AdapterStability) -> proto::AdapterStability {
    match s {
        AdapterStability::Registered => proto::AdapterStability::Registered,
        AdapterStability::Experimental => proto::AdapterStability::Experimental,
        AdapterStability::Stable => proto::AdapterStability::Stable,
        AdapterStability::Deprecated => proto::AdapterStability::Deprecated,
        AdapterStability::Retired => proto::AdapterStability::Retired,
    }
}

#[must_use]
pub const fn stability_from_proto(p: proto::AdapterStability) -> Option<AdapterStability> {
    match p {
        proto::AdapterStability::Unspecified => None,
        proto::AdapterStability::Registered => Some(AdapterStability::Registered),
        proto::AdapterStability::Experimental => Some(AdapterStability::Experimental),
        proto::AdapterStability::Stable => Some(AdapterStability::Stable),
        proto::AdapterStability::Deprecated => Some(AdapterStability::Deprecated),
        proto::AdapterStability::Retired => Some(AdapterStability::Retired),
    }
}

// ---------------------------------------------------------------------------
// QueueClass <-> proto enum
// ---------------------------------------------------------------------------

#[must_use]
pub const fn queue_class_to_proto(q: QueueClass) -> proto::QueueClass {
    match q {
        QueueClass::Interactive => proto::QueueClass::Interactive,
        QueueClass::AgentProposal => proto::QueueClass::AgentProposal,
        QueueClass::Background => proto::QueueClass::Background,
        QueueClass::RecoveryPriority => proto::QueueClass::RecoveryPriority,
    }
}

#[must_use]
pub const fn queue_class_from_proto(p: proto::QueueClass) -> Option<QueueClass> {
    match p {
        proto::QueueClass::Unspecified => None,
        proto::QueueClass::Interactive => Some(QueueClass::Interactive),
        proto::QueueClass::AgentProposal => Some(QueueClass::AgentProposal),
        proto::QueueClass::Background => Some(QueueClass::Background),
        proto::QueueClass::RecoveryPriority => Some(QueueClass::RecoveryPriority),
    }
}

// ---------------------------------------------------------------------------
// ExecutionFailureReason <-> proto enum
// ---------------------------------------------------------------------------

#[must_use]
pub const fn failure_reason_to_proto(r: ExecutionFailureReason) -> proto::ExecutionFailureReason {
    match r {
        ExecutionFailureReason::SandboxApplicationFailed => {
            proto::ExecutionFailureReason::SandboxApplicationFailed
        }
        ExecutionFailureReason::AdapterTimeout => proto::ExecutionFailureReason::AdapterTimeout,
        ExecutionFailureReason::AdapterPanic => proto::ExecutionFailureReason::AdapterPanic,
        ExecutionFailureReason::ResourceBudgetExceeded => {
            proto::ExecutionFailureReason::ResourceBudgetExceeded
        }
        ExecutionFailureReason::DependencyUnready => {
            proto::ExecutionFailureReason::DependencyUnready
        }
        ExecutionFailureReason::BackendUnavailable => {
            proto::ExecutionFailureReason::BackendUnavailable
        }
        ExecutionFailureReason::IdempotencyKeyReplayDetected => {
            proto::ExecutionFailureReason::IdempotencyKeyReplayDetected
        }
        ExecutionFailureReason::EnvelopeValidationFailed => {
            proto::ExecutionFailureReason::EnvelopeValidationFailed
        }
        ExecutionFailureReason::RollbackPreconditionFailed => {
            proto::ExecutionFailureReason::RollbackPreconditionFailed
        }
        ExecutionFailureReason::BindingExpired => proto::ExecutionFailureReason::BindingExpired,
        ExecutionFailureReason::BindingVoidedActionRevised => {
            proto::ExecutionFailureReason::BindingVoidedActionRevised
        }
        ExecutionFailureReason::AdapterRefused => proto::ExecutionFailureReason::AdapterRefused,
    }
}

#[must_use]
pub const fn failure_reason_from_proto(
    p: proto::ExecutionFailureReason,
) -> Option<ExecutionFailureReason> {
    match p {
        proto::ExecutionFailureReason::Unspecified => None,
        proto::ExecutionFailureReason::SandboxApplicationFailed => {
            Some(ExecutionFailureReason::SandboxApplicationFailed)
        }
        proto::ExecutionFailureReason::AdapterTimeout => {
            Some(ExecutionFailureReason::AdapterTimeout)
        }
        proto::ExecutionFailureReason::AdapterPanic => Some(ExecutionFailureReason::AdapterPanic),
        proto::ExecutionFailureReason::ResourceBudgetExceeded => {
            Some(ExecutionFailureReason::ResourceBudgetExceeded)
        }
        proto::ExecutionFailureReason::DependencyUnready => {
            Some(ExecutionFailureReason::DependencyUnready)
        }
        proto::ExecutionFailureReason::BackendUnavailable => {
            Some(ExecutionFailureReason::BackendUnavailable)
        }
        proto::ExecutionFailureReason::IdempotencyKeyReplayDetected => {
            Some(ExecutionFailureReason::IdempotencyKeyReplayDetected)
        }
        proto::ExecutionFailureReason::EnvelopeValidationFailed => {
            Some(ExecutionFailureReason::EnvelopeValidationFailed)
        }
        proto::ExecutionFailureReason::RollbackPreconditionFailed => {
            Some(ExecutionFailureReason::RollbackPreconditionFailed)
        }
        proto::ExecutionFailureReason::BindingExpired => {
            Some(ExecutionFailureReason::BindingExpired)
        }
        proto::ExecutionFailureReason::BindingVoidedActionRevised => {
            Some(ExecutionFailureReason::BindingVoidedActionRevised)
        }
        proto::ExecutionFailureReason::AdapterRefused => {
            Some(ExecutionFailureReason::AdapterRefused)
        }
    }
}

// ---------------------------------------------------------------------------
// RollbackOutcome <-> proto enum
// ---------------------------------------------------------------------------

#[must_use]
pub const fn rollback_outcome_to_proto(o: RollbackOutcome) -> proto::RollbackOutcome {
    match o {
        RollbackOutcome::NotAttempted => proto::RollbackOutcome::RollbackNotAttempted,
        RollbackOutcome::Succeeded => proto::RollbackOutcome::RollbackSucceeded,
        RollbackOutcome::Failed => proto::RollbackOutcome::RollbackFailedOutcome,
        RollbackOutcome::NotApplicable => proto::RollbackOutcome::RollbackNotApplicable,
    }
}

#[must_use]
pub const fn rollback_outcome_from_proto(p: proto::RollbackOutcome) -> Option<RollbackOutcome> {
    match p {
        proto::RollbackOutcome::Unspecified => None,
        proto::RollbackOutcome::RollbackNotAttempted => Some(RollbackOutcome::NotAttempted),
        proto::RollbackOutcome::RollbackSucceeded => Some(RollbackOutcome::Succeeded),
        proto::RollbackOutcome::RollbackFailedOutcome => Some(RollbackOutcome::Failed),
        proto::RollbackOutcome::RollbackNotApplicable => Some(RollbackOutcome::NotApplicable),
    }
}

// ---------------------------------------------------------------------------
// RuntimeErrorCode <-> proto enum
// ---------------------------------------------------------------------------

#[must_use]
pub const fn runtime_error_code_to_proto(c: RuntimeErrorCode) -> proto::RuntimeErrorCode {
    match c {
        RuntimeErrorCode::RuntimeOk => proto::RuntimeErrorCode::RuntimeOk,
        RuntimeErrorCode::InvalidEnvelope => proto::RuntimeErrorCode::InvalidEnvelope,
        RuntimeErrorCode::UnknownActionKind => proto::RuntimeErrorCode::UnknownActionKind,
        RuntimeErrorCode::UnknownAdapter => proto::RuntimeErrorCode::UnknownAdapter,
        RuntimeErrorCode::AdapterNotDispatchable => proto::RuntimeErrorCode::AdapterNotDispatchable,
        RuntimeErrorCode::PolicyDecisionUnavailable => {
            proto::RuntimeErrorCode::PolicyDecisionUnavailable
        }
        RuntimeErrorCode::ApprovalBindingInvalid => proto::RuntimeErrorCode::ApprovalBindingInvalid,
        RuntimeErrorCode::OverrideBindingInvalid => proto::RuntimeErrorCode::OverrideBindingInvalid,
        RuntimeErrorCode::BindingHashMismatch => proto::RuntimeErrorCode::BindingHashMismatch,
        RuntimeErrorCode::LifecycleIllegalTransition => {
            proto::RuntimeErrorCode::LifecycleIllegalTransition
        }
        RuntimeErrorCode::LifecycleTerminal => proto::RuntimeErrorCode::LifecycleTerminal,
        RuntimeErrorCode::IdempotencyReplay => proto::RuntimeErrorCode::IdempotencyReplay,
        RuntimeErrorCode::QueueBackpressureRejected => {
            proto::RuntimeErrorCode::QueueBackpressureRejected
        }
        RuntimeErrorCode::AdapterTimeoutBudgetExceeded => {
            proto::RuntimeErrorCode::AdapterTimeoutBudgetExceeded
        }
        RuntimeErrorCode::VerificationGrammarRejected => {
            proto::RuntimeErrorCode::VerificationGrammarRejected
        }
        RuntimeErrorCode::EvidenceLogUnavailable => proto::RuntimeErrorCode::EvidenceLogUnavailable,
        RuntimeErrorCode::EvidenceTamperDetected => proto::RuntimeErrorCode::EvidenceTamperDetected,
        RuntimeErrorCode::RuntimeDegraded => proto::RuntimeErrorCode::RuntimeDegraded,
        RuntimeErrorCode::ManifestSignatureInvalid => {
            proto::RuntimeErrorCode::ManifestSignatureInvalid
        }
        RuntimeErrorCode::RuntimeInternal => proto::RuntimeErrorCode::RuntimeInternal,
    }
}

#[must_use]
pub const fn runtime_error_code_from_proto(p: proto::RuntimeErrorCode) -> RuntimeErrorCode {
    match p {
        proto::RuntimeErrorCode::RuntimeOk => RuntimeErrorCode::RuntimeOk,
        proto::RuntimeErrorCode::InvalidEnvelope => RuntimeErrorCode::InvalidEnvelope,
        proto::RuntimeErrorCode::UnknownActionKind => RuntimeErrorCode::UnknownActionKind,
        proto::RuntimeErrorCode::UnknownAdapter => RuntimeErrorCode::UnknownAdapter,
        proto::RuntimeErrorCode::AdapterNotDispatchable => RuntimeErrorCode::AdapterNotDispatchable,
        proto::RuntimeErrorCode::PolicyDecisionUnavailable => {
            RuntimeErrorCode::PolicyDecisionUnavailable
        }
        proto::RuntimeErrorCode::ApprovalBindingInvalid => RuntimeErrorCode::ApprovalBindingInvalid,
        proto::RuntimeErrorCode::OverrideBindingInvalid => RuntimeErrorCode::OverrideBindingInvalid,
        proto::RuntimeErrorCode::BindingHashMismatch => RuntimeErrorCode::BindingHashMismatch,
        proto::RuntimeErrorCode::LifecycleIllegalTransition => {
            RuntimeErrorCode::LifecycleIllegalTransition
        }
        proto::RuntimeErrorCode::LifecycleTerminal => RuntimeErrorCode::LifecycleTerminal,
        proto::RuntimeErrorCode::IdempotencyReplay => RuntimeErrorCode::IdempotencyReplay,
        proto::RuntimeErrorCode::QueueBackpressureRejected => {
            RuntimeErrorCode::QueueBackpressureRejected
        }
        proto::RuntimeErrorCode::AdapterTimeoutBudgetExceeded => {
            RuntimeErrorCode::AdapterTimeoutBudgetExceeded
        }
        proto::RuntimeErrorCode::VerificationGrammarRejected => {
            RuntimeErrorCode::VerificationGrammarRejected
        }
        proto::RuntimeErrorCode::EvidenceLogUnavailable => RuntimeErrorCode::EvidenceLogUnavailable,
        proto::RuntimeErrorCode::EvidenceTamperDetected => RuntimeErrorCode::EvidenceTamperDetected,
        proto::RuntimeErrorCode::RuntimeDegraded => RuntimeErrorCode::RuntimeDegraded,
        proto::RuntimeErrorCode::ManifestSignatureInvalid => {
            RuntimeErrorCode::ManifestSignatureInvalid
        }
        proto::RuntimeErrorCode::RuntimeInternal => RuntimeErrorCode::RuntimeInternal,
    }
}

// ---------------------------------------------------------------------------
// AdapterActionDeclaration <-> proto
// ---------------------------------------------------------------------------

/// Convert a Rust [`AdapterActionDeclaration`] into its wire form.
///
/// `target_schema` / `response_schema` are opaque JSON values on the Rust
/// side; on the wire we render them as serialised JSON strings so the proto
/// IDL does not have to track an open-ended schema vocabulary.
#[must_use]
pub fn adapter_action_declaration_to_proto(
    d: &AdapterActionDeclaration,
) -> proto::AdapterActionDeclaration {
    proto::AdapterActionDeclaration {
        action_kind: d.action_kind.clone(),
        target_schema_json: d.target_schema.to_string(),
        response_schema_json: d.response_schema.to_string(),
        rollback_strategy: d.rollback_strategy.clone(),
        timeout_seconds: d.timeout_seconds,
        template_string: d.template_string.clone().unwrap_or_default(),
        template_substitution_variables: d.template_substitution_variables.clone(),
    }
}

/// Convert the wire form back into a Rust [`AdapterActionDeclaration`].
///
/// # Errors
///
/// Returns [`RuntimeError::ManifestInvalid`] when `target_schema_json` or
/// `response_schema_json` is not a valid JSON value.
pub fn adapter_action_declaration_from_proto(
    p: &proto::AdapterActionDeclaration,
) -> Result<AdapterActionDeclaration, RuntimeError> {
    let target_schema: serde_json::Value = serde_json::from_str(&p.target_schema_json)
        .map_err(|e| RuntimeError::ManifestInvalid(format!("target_schema_json decode: {e}")))?;
    let response_schema: serde_json::Value = serde_json::from_str(&p.response_schema_json)
        .map_err(|e| RuntimeError::ManifestInvalid(format!("response_schema_json decode: {e}")))?;
    Ok(AdapterActionDeclaration {
        action_kind: p.action_kind.clone(),
        target_schema,
        response_schema,
        rollback_strategy: p.rollback_strategy.clone(),
        timeout_seconds: p.timeout_seconds,
        template_string: if p.template_string.is_empty() {
            None
        } else {
            Some(p.template_string.clone())
        },
        template_substitution_variables: p.template_substitution_variables.clone(),
    })
}

// ---------------------------------------------------------------------------
// AdapterManifest <-> proto
// ---------------------------------------------------------------------------

/// Convert a Rust [`AdapterManifest`] into its wire form.
#[must_use]
pub fn adapter_manifest_to_proto(m: &AdapterManifest) -> proto::AdapterManifest {
    proto::AdapterManifest {
        adapter_id: m.adapter_id.clone(),
        adapter_version: m.adapter_version.clone(),
        vendor: m.vendor.clone(),
        name: m.name.clone(),
        declared_stability: i32::from(stability_to_proto(m.declared_stability)),
        io_mode: i32::from(io_mode_to_proto(m.io_mode)),
        dispatch_kind: i32::from(dispatch_kind_to_proto(m.dispatch_kind)),
        declared_actions: m
            .declared_actions
            .iter()
            .map(adapter_action_declaration_to_proto)
            .collect(),
        declared_invariants_supported: m.declared_invariants_supported.clone(),
        default_adapter_timeout_seconds: m.default_adapter_timeout_seconds,
        default_sandbox_profile_id: m.default_sandbox_profile_id.clone(),
        adapter_signature: m.adapter_signature.clone(),
        signing_key_id: m.signing_key_id.clone(),
        manifest_created_at: Some(datetime_to_proto(m.manifest_created_at)),
        manifest_expires_at: Some(datetime_to_proto(m.manifest_expires_at)),
    }
}

/// Convert the wire form back into a Rust [`AdapterManifest`].
///
/// # Errors
///
/// Returns [`RuntimeError::ManifestInvalid`] when any required nested field
/// (closed enum, declared action JSON schema, ...) fails to decode.
pub fn adapter_manifest_from_proto(
    p: &proto::AdapterManifest,
) -> Result<AdapterManifest, RuntimeError> {
    let declared_stability = stability_from_proto(
        proto::AdapterStability::try_from(p.declared_stability).map_err(|_| {
            RuntimeError::ManifestInvalid(format!("declared_stability={}", p.declared_stability))
        })?,
    )
    .ok_or_else(|| RuntimeError::ManifestInvalid("declared_stability=UNSPECIFIED".into()))?;
    let io_mode = io_mode_from_proto(
        proto::AdapterIoMode::try_from(p.io_mode)
            .map_err(|_| RuntimeError::ManifestInvalid(format!("io_mode={}", p.io_mode)))?,
    )
    .ok_or_else(|| RuntimeError::ManifestInvalid("io_mode=UNSPECIFIED".into()))?;
    let dispatch_kind = dispatch_kind_from_proto(
        proto::ActionDispatchKind::try_from(p.dispatch_kind).map_err(|_| {
            RuntimeError::ManifestInvalid(format!("dispatch_kind={}", p.dispatch_kind))
        })?,
    )
    .ok_or_else(|| RuntimeError::ManifestInvalid("dispatch_kind=UNSPECIFIED".into()))?;
    let declared_actions = p
        .declared_actions
        .iter()
        .map(adapter_action_declaration_from_proto)
        .collect::<Result<Vec<_>, _>>()?;
    let manifest_created_at = p
        .manifest_created_at
        .map_or_else(unix_epoch, datetime_from_proto);
    let manifest_expires_at = p
        .manifest_expires_at
        .map_or_else(unix_epoch, datetime_from_proto);
    Ok(AdapterManifest {
        adapter_id: p.adapter_id.clone(),
        adapter_version: p.adapter_version.clone(),
        vendor: p.vendor.clone(),
        name: p.name.clone(),
        declared_stability,
        io_mode,
        dispatch_kind,
        declared_actions,
        declared_invariants_supported: p.declared_invariants_supported.clone(),
        default_adapter_timeout_seconds: p.default_adapter_timeout_seconds,
        default_sandbox_profile_id: p.default_sandbox_profile_id.clone(),
        adapter_signature: p.adapter_signature.clone(),
        signing_key_id: p.signing_key_id.clone(),
        manifest_created_at,
        manifest_expires_at,
    })
}

// ---------------------------------------------------------------------------
// RegisteredAdapter <-> proto
// ---------------------------------------------------------------------------

#[must_use]
pub fn registered_adapter_to_proto(r: &RegisteredAdapter) -> proto::RegisteredAdapter {
    proto::RegisteredAdapter {
        manifest: Some(adapter_manifest_to_proto(&r.manifest)),
        registered_at: Some(datetime_to_proto(r.registered_at)),
    }
}

/// # Errors
///
/// Returns [`RuntimeError::ManifestInvalid`] when the embedded
/// [`AdapterManifest`] is missing or fails decoding.
pub fn registered_adapter_from_proto(
    p: &proto::RegisteredAdapter,
) -> Result<RegisteredAdapter, RuntimeError> {
    let manifest_proto = p.manifest.as_ref().ok_or_else(|| {
        RuntimeError::ManifestInvalid("registered_adapter.manifest missing".into())
    })?;
    let manifest = adapter_manifest_from_proto(manifest_proto)?;
    let registered_at = p.registered_at.map_or_else(unix_epoch, datetime_from_proto);
    Ok(RegisteredAdapter {
        manifest,
        registered_at,
    })
}

// ---------------------------------------------------------------------------
// ActionContext <-> proto
// ---------------------------------------------------------------------------

#[must_use]
pub fn action_context_to_proto(c: &ActionContext) -> proto::ActionContext {
    proto::ActionContext {
        action_id: c.action_id.to_string(),
        status: i32::from(lifecycle_state_to_proto(c.status)),
        dispatch_kind: i32::from(dispatch_kind_to_proto(c.dispatch_kind)),
        queue_class: i32::from(queue_class_to_proto(c.queue_class)),
        created_at: Some(datetime_to_proto(c.created_at)),
        last_updated_at: Some(datetime_to_proto(c.last_updated_at)),
        // `0` (`_UNSPECIFIED`) for None is the proto3 convention; the
        // receiver re-projects to `Option<...>` via the proto enum's
        // `Unspecified` arm.
        error: c.error.map_or(0, |r| i32::from(failure_reason_to_proto(r))),
        rollback_outcome: c
            .rollback_outcome
            .map_or(0, |o| i32::from(rollback_outcome_to_proto(o))),
        evidence_chain: c.evidence_chain.clone(),
    }
}

/// # Errors
///
/// Returns [`RuntimeError::Internal`] when the `action_id` string fails to
/// parse back into an `aios_action::ActionId`.
pub fn action_context_from_proto(p: &proto::ActionContext) -> Result<ActionContext, RuntimeError> {
    let action_id = aios_action::ActionId::parse(&p.action_id)
        .map_err(|e| RuntimeError::Internal(format!("action_id parse: {e}")))?;
    let status = lifecycle_state_from_proto(
        proto::ActionLifecycleState::try_from(p.status)
            .map_err(|_| RuntimeError::Internal(format!("status={}", p.status)))?,
    )
    .ok_or_else(|| RuntimeError::Internal("status=UNSPECIFIED".into()))?;
    let dispatch_kind = dispatch_kind_from_proto(
        proto::ActionDispatchKind::try_from(p.dispatch_kind)
            .map_err(|_| RuntimeError::Internal(format!("dispatch_kind={}", p.dispatch_kind)))?,
    )
    .ok_or_else(|| RuntimeError::Internal("dispatch_kind=UNSPECIFIED".into()))?;
    let queue_class = queue_class_from_proto(
        proto::QueueClass::try_from(p.queue_class)
            .map_err(|_| RuntimeError::Internal(format!("queue_class={}", p.queue_class)))?,
    )
    .ok_or_else(|| RuntimeError::Internal("queue_class=UNSPECIFIED".into()))?;
    let created_at = p.created_at.map_or_else(unix_epoch, datetime_from_proto);
    let last_updated_at = p
        .last_updated_at
        .map_or_else(unix_epoch, datetime_from_proto);
    let error = proto::ExecutionFailureReason::try_from(p.error)
        .ok()
        .and_then(failure_reason_from_proto);
    let rollback_outcome = proto::RollbackOutcome::try_from(p.rollback_outcome)
        .ok()
        .and_then(rollback_outcome_from_proto);
    Ok(ActionContext {
        action_id,
        status,
        dispatch_kind,
        queue_class,
        created_at,
        last_updated_at,
        error,
        rollback_outcome,
        evidence_chain: p.evidence_chain.clone(),
    })
}

// ---------------------------------------------------------------------------
// envelope_proto wire form (JSON placeholder per task #26)
// ---------------------------------------------------------------------------

/// Encode an [`aios_action::ActionEnvelope`] into the wire-bytes form carried
/// by `ValidateActionRequest.envelope_proto` / `ExecuteActionRequest.envelope_proto`.
///
/// Per task #26 in the .ai tracker, the in-tree wire format is the canonical
/// `serde_json` representation of the envelope. When `aios-action` ships its
/// own proto IDL, this function is the single touch point — the rest of the
/// service module references it by name. Pattern mirrors aios-policy T-023
/// verbatim.
///
/// # Errors
///
/// Returns `tonic::Status::internal` when serialisation fails. In practice
/// this cannot happen for a well-typed `ActionEnvelope` (the serde derive is
/// infallible over the value).
pub fn envelope_to_bytes(env: &aios_action::ActionEnvelope) -> Result<Vec<u8>, tonic::Status> {
    serde_json::to_vec(env)
        .map_err(|e| tonic::Status::internal(format!("envelope serialize failed: {e}")))
}

/// Decode the wire-bytes form into an [`aios_action::ActionEnvelope`].
///
/// # Errors
///
/// Returns `tonic::Status::invalid_argument` when the bytes are empty or
/// when `serde_json` cannot deserialize the payload into an `ActionEnvelope`.
pub fn envelope_from_bytes(bytes: &[u8]) -> Result<aios_action::ActionEnvelope, tonic::Status> {
    if bytes.is_empty() {
        return Err(tonic::Status::invalid_argument(
            "envelope_proto is empty (expected serialized aios.action.v1alpha1.ActionEnvelope)",
        ));
    }
    serde_json::from_slice(bytes).map_err(|e| {
        tonic::Status::invalid_argument(format!(
            "envelope_proto deserialize failed (JSON placeholder per task #26): {e}"
        ))
    })
}

// ---------------------------------------------------------------------------
// RuntimeError -> tonic::Status (status mapping table)
// ---------------------------------------------------------------------------

/// Map a typed [`RuntimeError`] onto a `tonic::Status` per the closed
/// [`RuntimeErrorCode`] table.
///
/// The mapping table:
///
/// | `RuntimeError` variant              | `tonic::Code`           | `RuntimeErrorCode`              |
/// | ----------------------------------- | ----------------------- | ------------------------------- |
/// | `ActionNotFound`                    | `NotFound`              | `RuntimeInternal`               |
/// | `InvalidTransition { .. }`          | `FailedPrecondition`    | `LifecycleIllegalTransition`    |
/// | `AdapterUnknown(_)`                 | `NotFound`              | `UnknownAdapter`                |
/// | `AdapterSignatureInvalid`           | `PermissionDenied`      | `ManifestSignatureInvalid`      |
/// | `AdapterUnknownAuthority(_)`        | `PermissionDenied`      | `ManifestSignatureInvalid`      |
/// | `AdapterAlreadyRegistered(_)`       | `AlreadyExists`         | `RuntimeInternal`               |
/// | `ManifestInvalid(_)`                | `InvalidArgument`       | `ManifestSignatureInvalid`      |
/// | `QueueFull(_)`                      | `ResourceExhausted`     | `QueueBackpressureRejected`     |
/// | `RateLimited(_)`                    | `ResourceExhausted`     | `QueueBackpressureRejected`     |
/// | `PolicyEvalFailed(_)`               | `FailedPrecondition`    | `PolicyDecisionUnavailable`     |
/// | `EvidenceEmitFailed(_)`             | `Internal`              | `EvidenceLogUnavailable`        |
/// | `Internal(_)`                       | `Internal`              | `RuntimeInternal`               |
///
/// Code-only API: the wire layer consumes the `Status` directly; the
/// `RuntimeErrorCode` projection is documented here for parity with the
/// closed §3.8 enum and used by tests.
#[must_use]
pub fn runtime_error_to_status(e: &RuntimeError) -> tonic::Status {
    match e {
        RuntimeError::ActionNotFound(id) => {
            tonic::Status::not_found(format!("action not found: {id}"))
        }
        RuntimeError::InvalidTransition { from, to } => tonic::Status::failed_precondition(
            format!("illegal lifecycle transition: {from:?} -> {to:?}"),
        ),
        RuntimeError::AdapterUnknown(id) => {
            tonic::Status::not_found(format!("unknown adapter: {id}"))
        }
        RuntimeError::AdapterSignatureInvalid => {
            tonic::Status::permission_denied("adapter manifest signature invalid")
        }
        RuntimeError::AdapterUnknownAuthority(id) => tonic::Status::permission_denied(format!(
            "adapter manifest unknown signing authority: {id}"
        )),
        RuntimeError::AdapterAlreadyRegistered(id) => {
            tonic::Status::already_exists(format!("adapter already registered: {id}"))
        }
        RuntimeError::ManifestInvalid(msg) => {
            tonic::Status::invalid_argument(format!("adapter manifest invalid: {msg}"))
        }
        RuntimeError::QueueFull(class) => {
            tonic::Status::resource_exhausted(format!("dispatch queue full for class: {class:?}"))
        }
        RuntimeError::RateLimited(subject) => {
            tonic::Status::resource_exhausted(format!("subject rate-limited: {subject}"))
        }
        RuntimeError::PolicyEvalFailed(msg) => {
            tonic::Status::failed_precondition(format!("policy evaluation failed: {msg}"))
        }
        RuntimeError::EvidenceEmitFailed(msg) => {
            tonic::Status::internal(format!("evidence emission failed: {msg}"))
        }
        RuntimeError::Internal(msg) => {
            tonic::Status::internal(format!("runtime internal error: {msg}"))
        }
    }
}

/// Projection of a typed [`RuntimeError`] onto its [`RuntimeErrorCode`] wire
/// counterpart. Used by tests that assert the mapping table; the wire layer
/// itself uses [`runtime_error_to_status`].
#[must_use]
pub const fn runtime_error_to_code(e: &RuntimeError) -> RuntimeErrorCode {
    match e {
        RuntimeError::ActionNotFound(_)
        | RuntimeError::AdapterAlreadyRegistered(_)
        | RuntimeError::Internal(_) => RuntimeErrorCode::RuntimeInternal,
        RuntimeError::InvalidTransition { .. } => RuntimeErrorCode::LifecycleIllegalTransition,
        RuntimeError::AdapterUnknown(_) => RuntimeErrorCode::UnknownAdapter,
        RuntimeError::AdapterSignatureInvalid
        | RuntimeError::AdapterUnknownAuthority(_)
        | RuntimeError::ManifestInvalid(_) => RuntimeErrorCode::ManifestSignatureInvalid,
        RuntimeError::QueueFull(_) | RuntimeError::RateLimited(_) => {
            RuntimeErrorCode::QueueBackpressureRejected
        }
        RuntimeError::PolicyEvalFailed(_) => RuntimeErrorCode::PolicyDecisionUnavailable,
        RuntimeError::EvidenceEmitFailed(_) => RuntimeErrorCode::EvidenceLogUnavailable,
    }
}

#[cfg(test)]
#[allow(
    clippy::expect_used,
    clippy::panic,
    clippy::unwrap_used,
    reason = "test code; panic-on-failure is the idiomatic test signal"
)]
mod tests {
    use super::*;

    #[test]
    fn datetime_round_trip() {
        let now = Utc::now();
        let proto = datetime_to_proto(now);
        let back = datetime_from_proto(proto);
        assert_eq!(now.timestamp(), back.timestamp());
    }

    #[test]
    fn lifecycle_state_round_trip_all_variants() {
        use strum::IntoEnumIterator;
        for s in ActionLifecycleState::iter() {
            let p = lifecycle_state_to_proto(s);
            let back = lifecycle_state_from_proto(p).expect("non-UNSPECIFIED");
            assert_eq!(s, back);
        }
    }

    #[test]
    fn dispatch_kind_round_trip_all_variants() {
        use strum::IntoEnumIterator;
        for k in ActionDispatchKind::iter() {
            let p = dispatch_kind_to_proto(k);
            let back = dispatch_kind_from_proto(p).expect("non-UNSPECIFIED");
            assert_eq!(k, back);
        }
    }

    #[test]
    fn queue_class_round_trip_all_variants() {
        use strum::IntoEnumIterator;
        for q in QueueClass::iter() {
            let p = queue_class_to_proto(q);
            let back = queue_class_from_proto(p).expect("non-UNSPECIFIED");
            assert_eq!(q, back);
        }
    }

    #[test]
    fn rollback_outcome_round_trip_all_variants() {
        use strum::IntoEnumIterator;
        for o in RollbackOutcome::iter() {
            let p = rollback_outcome_to_proto(o);
            let back = rollback_outcome_from_proto(p).expect("non-UNSPECIFIED");
            assert_eq!(o, back);
        }
    }

    #[test]
    fn execution_failure_reason_round_trip_all_variants() {
        use strum::IntoEnumIterator;
        for r in ExecutionFailureReason::iter() {
            let p = failure_reason_to_proto(r);
            let back = failure_reason_from_proto(p).expect("non-UNSPECIFIED");
            assert_eq!(r, back);
        }
    }

    #[test]
    fn runtime_error_code_round_trip_all_variants() {
        use strum::IntoEnumIterator;
        for c in RuntimeErrorCode::iter() {
            let p = runtime_error_code_to_proto(c);
            let back = runtime_error_code_from_proto(p);
            assert_eq!(c, back);
        }
    }

    #[test]
    fn runtime_error_status_mapping_action_not_found_is_not_found() {
        let id = aios_action::ActionId::new();
        let e = RuntimeError::ActionNotFound(id);
        let s = runtime_error_to_status(&e);
        assert_eq!(s.code(), tonic::Code::NotFound);
    }

    #[test]
    fn runtime_error_status_mapping_invalid_transition_is_failed_precondition() {
        let e = RuntimeError::InvalidTransition {
            from: ActionLifecycleState::Succeeded,
            to: ActionLifecycleState::Executing,
        };
        let s = runtime_error_to_status(&e);
        assert_eq!(s.code(), tonic::Code::FailedPrecondition);
    }

    #[test]
    fn runtime_error_status_mapping_adapter_signature_invalid_is_permission_denied() {
        let s = runtime_error_to_status(&RuntimeError::AdapterSignatureInvalid);
        assert_eq!(s.code(), tonic::Code::PermissionDenied);
    }

    #[test]
    fn runtime_error_status_mapping_queue_full_is_resource_exhausted() {
        let s = runtime_error_to_status(&RuntimeError::QueueFull(QueueClass::AgentProposal));
        assert_eq!(s.code(), tonic::Code::ResourceExhausted);
    }

    #[test]
    fn runtime_error_status_mapping_policy_eval_failed_is_failed_precondition() {
        let s = runtime_error_to_status(&RuntimeError::PolicyEvalFailed("kernel down".into()));
        assert_eq!(s.code(), tonic::Code::FailedPrecondition);
    }

    #[test]
    fn runtime_error_status_mapping_evidence_emit_failed_is_internal() {
        let s = runtime_error_to_status(&RuntimeError::EvidenceEmitFailed("WAL stall".into()));
        assert_eq!(s.code(), tonic::Code::Internal);
    }

    #[test]
    fn runtime_error_to_code_projection_table() {
        assert_eq!(
            runtime_error_to_code(&RuntimeError::AdapterUnknown("x".into())),
            RuntimeErrorCode::UnknownAdapter
        );
        assert_eq!(
            runtime_error_to_code(&RuntimeError::AdapterSignatureInvalid),
            RuntimeErrorCode::ManifestSignatureInvalid
        );
        assert_eq!(
            runtime_error_to_code(&RuntimeError::QueueFull(QueueClass::Interactive)),
            RuntimeErrorCode::QueueBackpressureRejected
        );
        assert_eq!(
            runtime_error_to_code(&RuntimeError::PolicyEvalFailed("nope".into())),
            RuntimeErrorCode::PolicyDecisionUnavailable
        );
        assert_eq!(
            runtime_error_to_code(&RuntimeError::EvidenceEmitFailed("stall".into())),
            RuntimeErrorCode::EvidenceLogUnavailable
        );
    }
}
