//! S20 closed vocabulary types for the Native AI Control Plane Terminal.
//!
//! Every enum derives [`EnumIter`] + [`EnumCount`] for compile-time
//! exhaustiveness checking and round-trip test coverage. Serde wire form is
//! `SCREAMING_SNAKE_CASE` across the entire crate.

use serde::{Deserialize, Serialize};
use strum_macros::{EnumCount, EnumIter};

/// Terminal surface mode — determines how user input is parsed and executed.
///
/// Per S20 §7: `Lx` is a direct POSIX shell, `Mix` is natural language by
/// default with `LX:` escape, and `Ai` accepts only AI intents and typed
/// actions (raw shell text is inert).
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, EnumIter, EnumCount,
)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum TerminalMode {
    /// Direct Linux/POSIX shell — AI does not reinterpret commands.
    Lx,
    /// Natural language by default; `LX:` prefix required for raw shell.
    Mix,
    /// AI intent mode only — raw shell text is inert, not executed.
    Ai,
}

/// Seven-state lifecycle FSM for an AI action proposal.
///
/// Transitions per S20 §3 (TypedActionCompiler → PolicyPreflightGate →
/// HumanOversightGate → AIExecutionBroker → VerificationRunner →
/// AIEvidenceWriter).
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, EnumIter, EnumCount,
)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ProposalState {
    /// Proposal was created but not yet submitted for review.
    Draft,
    /// Proposal has been submitted to the pipeline.
    Proposed,
    /// Policy Kernel is evaluating the proposal.
    UnderReview,
    /// Human operator approved the proposal.
    Approved,
    /// Approved proposal has been executed by the capability runtime.
    Executed,
    /// Proposal was rejected (by policy or by human operator).
    Rejected,
    /// Proposal was revoked after approval but before execution.
    Revoked,
}

/// Marker indicating whether terminal output was produced by AI or a human.
///
/// S20 §10 Transparency control: every piece of AI-generated output must be
/// visibly distinguishable from human-written output.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, EnumIter, EnumCount,
)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum AiMarker {
    /// Text written by a human operator with no AI involvement.
    HumanWritten,
    /// Text proposed by AI but not yet reviewed.
    AiProposed,
    /// Text generated by AI with no human review.
    AiGenerated,
    /// AI output that has been reviewed by a human.
    HumanReviewed,
    /// AI output that has been reviewed and verified by a human.
    AiGeneratedHumanVerified,
}

/// Classification of user input intent in the terminal.
///
/// Produced by the [`PromptBoundaryClassifier`] (S20 §3) before the input
/// reaches the AI cognitive core.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, EnumIter, EnumCount,
)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum UserIntentClass {
    /// Shell command or explicit `LX:` prefix instruction.
    DirectCommand,
    /// Free-form natural language question about system state.
    NaturalLanguageQuery,
    /// Explicit request for AI assistance.
    AiAssistRequest,
    /// Request to generate code or scripts.
    CodeGeneration,
    /// Request to change system configuration.
    SystemConfiguration,
    /// Intent could not be classified with sufficient confidence.
    Unknown,
}

/// Outcome of a dispatched action — reported after execution completes.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize, EnumIter, EnumCount,
)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ActionOutcome {
    /// Action executed successfully.
    Success,
    /// Action executed but some post-conditions were not met.
    PartialSuccess,
    /// Action failed during execution.
    Failure,
    /// Action was rejected by policy or operator before execution.
    Rejected,
    /// Action timed out during execution.
    Timeout,
    /// Action was cancelled by the operator mid-execution.
    Cancelled,
}

impl ProposalState {
    /// Returns `true` if this state is terminal — no further transitions
    /// are possible.
    #[must_use]
    pub fn is_terminal(self) -> bool {
        matches!(self, Self::Executed | Self::Rejected | Self::Revoked)
    }

    /// Returns `true` if a transition from `self` to `next` is valid per the
    /// 7-state FSM defined in S20 §3.
    #[must_use]
    pub fn can_transition_to(self, next: Self) -> bool {
        matches!(
            (self, next),
            (Self::Draft, Self::Proposed)
                | (Self::Proposed, Self::UnderReview)
                | (Self::UnderReview, Self::Approved)
                | (Self::UnderReview, Self::Rejected)
                | (Self::Approved, Self::Executed)
                | (Self::Approved, Self::Revoked)
                | (Self::Rejected, Self::Draft)
                | (Self::Revoked, Self::Draft)
        )
    }
}

impl UserIntentClass {
    /// Returns `true` if this intent class requires AI processing.
    #[must_use]
    pub fn requires_ai_processing(self) -> bool {
        matches!(
            self,
            Self::NaturalLanguageQuery | Self::AiAssistRequest | Self::CodeGeneration
        )
    }
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    reason = "panic-on-failure is the idiomatic test signal"
)]
mod tests {
    use super::*;
    use strum::{EnumCount, IntoEnumIterator};

    #[test]
    fn terminal_mode_has_three_variants() {
        assert_eq!(TerminalMode::COUNT, 3);
        assert_eq!(TerminalMode::iter().count(), 3);
    }

    #[test]
    fn proposal_state_has_seven_variants() {
        assert_eq!(ProposalState::COUNT, 7);
        assert_eq!(ProposalState::iter().count(), 7);
    }

    #[test]
    fn ai_marker_has_five_variants() {
        assert_eq!(AiMarker::COUNT, 5);
        assert_eq!(AiMarker::iter().count(), 5);
    }

    #[test]
    fn user_intent_class_has_six_variants() {
        assert_eq!(UserIntentClass::COUNT, 6);
        assert_eq!(UserIntentClass::iter().count(), 6);
    }

    #[test]
    fn action_outcome_has_six_variants() {
        assert_eq!(ActionOutcome::COUNT, 6);
        assert_eq!(ActionOutcome::iter().count(), 6);
    }

    // ── serde round-trip ──

    #[test]
    fn terminal_mode_serde_round_trip() {
        for variant in TerminalMode::iter() {
            let json = serde_json::to_string(&variant).unwrap();
            let back: TerminalMode = serde_json::from_str(&json).unwrap();
            assert_eq!(variant, back, "round-trip failed for {variant:?}");
        }
    }

    #[test]
    fn proposal_state_serde_round_trip() {
        for variant in ProposalState::iter() {
            let json = serde_json::to_string(&variant).unwrap();
            let back: ProposalState = serde_json::from_str(&json).unwrap();
            assert_eq!(variant, back, "round-trip failed for {variant:?}");
        }
    }

    #[test]
    fn ai_marker_serde_round_trip() {
        for variant in AiMarker::iter() {
            let json = serde_json::to_string(&variant).unwrap();
            let back: AiMarker = serde_json::from_str(&json).unwrap();
            assert_eq!(variant, back, "round-trip failed for {variant:?}");
        }
    }

    #[test]
    fn user_intent_class_serde_round_trip() {
        for variant in UserIntentClass::iter() {
            let json = serde_json::to_string(&variant).unwrap();
            let back: UserIntentClass = serde_json::from_str(&json).unwrap();
            assert_eq!(variant, back, "round-trip failed for {variant:?}");
        }
    }

    #[test]
    fn action_outcome_serde_round_trip() {
        for variant in ActionOutcome::iter() {
            let json = serde_json::to_string(&variant).unwrap();
            let back: ActionOutcome = serde_json::from_str(&json).unwrap();
            assert_eq!(variant, back, "round-trip failed for {variant:?}");
        }
    }

    // ── serde exact wire form ──

    #[test]
    fn terminal_mode_wire_form() {
        assert_eq!(serde_json::to_string(&TerminalMode::Lx).unwrap(), "\"LX\"");
        assert_eq!(serde_json::to_string(&TerminalMode::Mix).unwrap(), "\"MIX\"");
        assert_eq!(serde_json::to_string(&TerminalMode::Ai).unwrap(), "\"AI\"");
    }

    #[test]
    fn proposal_state_wire_form() {
        assert_eq!(
            serde_json::to_string(&ProposalState::Draft).unwrap(),
            "\"DRAFT\""
        );
        assert_eq!(
            serde_json::to_string(&ProposalState::Executed).unwrap(),
            "\"EXECUTED\""
        );
        assert_eq!(
            serde_json::to_string(&ProposalState::Approved).unwrap(),
            "\"APPROVED\""
        );
    }

    #[test]
    fn ai_marker_wire_form() {
        assert_eq!(
            serde_json::to_string(&AiMarker::HumanWritten).unwrap(),
            "\"HUMAN_WRITTEN\""
        );
        assert_eq!(
            serde_json::to_string(&AiMarker::AiGeneratedHumanVerified).unwrap(),
            "\"AI_GENERATED_HUMAN_VERIFIED\""
        );
    }

    #[test]
    fn user_intent_class_wire_form() {
        assert_eq!(
            serde_json::to_string(&UserIntentClass::DirectCommand).unwrap(),
            "\"DIRECT_COMMAND\""
        );
        assert_eq!(
            serde_json::to_string(&UserIntentClass::Unknown).unwrap(),
            "\"UNKNOWN\""
        );
    }

    #[test]
    fn action_outcome_wire_form() {
        assert_eq!(
            serde_json::to_string(&ActionOutcome::Success).unwrap(),
            "\"SUCCESS\""
        );
        assert_eq!(
            serde_json::to_string(&ActionOutcome::PartialSuccess).unwrap(),
            "\"PARTIAL_SUCCESS\""
        );
    }

    // ── FSM transition tests ──

    #[test]
    fn proposal_state_draft_to_proposed() {
        assert!(ProposalState::Draft.can_transition_to(ProposalState::Proposed));
    }

    #[test]
    fn proposal_state_proposed_to_under_review() {
        assert!(ProposalState::Proposed.can_transition_to(ProposalState::UnderReview));
    }

    #[test]
    fn proposal_state_under_review_to_approved() {
        assert!(ProposalState::UnderReview.can_transition_to(ProposalState::Approved));
    }

    #[test]
    fn proposal_state_under_review_to_rejected() {
        assert!(ProposalState::UnderReview.can_transition_to(ProposalState::Rejected));
    }

    #[test]
    fn proposal_state_approved_to_executed() {
        assert!(ProposalState::Approved.can_transition_to(ProposalState::Executed));
    }

    #[test]
    fn proposal_state_approved_to_revoked() {
        assert!(ProposalState::Approved.can_transition_to(ProposalState::Revoked));
    }

    #[test]
    fn proposal_state_rejected_back_to_draft() {
        assert!(ProposalState::Rejected.can_transition_to(ProposalState::Draft));
    }

    #[test]
    fn proposal_state_revoked_back_to_draft() {
        assert!(ProposalState::Revoked.can_transition_to(ProposalState::Draft));
    }

    #[test]
    fn proposal_state_terminal_no_forward() {
        assert!(!ProposalState::Executed.can_transition_to(ProposalState::Approved));
        assert!(!ProposalState::Executed.can_transition_to(ProposalState::Draft));
        assert!(!ProposalState::Rejected.can_transition_to(ProposalState::Approved));
        assert!(!ProposalState::Revoked.can_transition_to(ProposalState::Executed));
    }

    #[test]
    fn proposal_state_terminal_check() {
        assert!(ProposalState::Executed.is_terminal());
        assert!(ProposalState::Rejected.is_terminal());
        assert!(ProposalState::Revoked.is_terminal());
        assert!(!ProposalState::Draft.is_terminal());
        assert!(!ProposalState::Proposed.is_terminal());
        assert!(!ProposalState::UnderReview.is_terminal());
        assert!(!ProposalState::Approved.is_terminal());
    }

    #[test]
    fn user_intent_requires_ai_processing() {
        assert!(UserIntentClass::NaturalLanguageQuery.requires_ai_processing());
        assert!(UserIntentClass::AiAssistRequest.requires_ai_processing());
        assert!(UserIntentClass::CodeGeneration.requires_ai_processing());
        assert!(!UserIntentClass::DirectCommand.requires_ai_processing());
        assert!(!UserIntentClass::SystemConfiguration.requires_ai_processing());
        assert!(!UserIntentClass::Unknown.requires_ai_processing());
    }
}
